
package view;

import model.EntryExitRecord;
import model.ParkingLot;
import model.SecurityGuard;
import model.ResidentManager;
import model.VisitorManager;
import utils.JsonDataManager; 
import java.util.Date;
import javax.swing.JOptionPane;
import model.ParkingControlSystem;
import parkingcontrolsystem.library.ParkingSpaceLibrary;


/**
 *
 * @author Emily Calle, @ESPE
 */
public class EntryExitForm extends javax.swing.JFrame {

    private final SecurityGuard guard;
    private final ParkingLot parkingLot;
    private final EntryExitRecord entryExitSystem;
    
    
    public EntryExitForm(SecurityGuard guard, ParkingLot parkingLot, EntryExitRecord entryExitSystem) {
        initComponents();
        
        this.guard = guard;
        this.parkingLot = parkingLot;
        this.entryExitSystem = entryExitSystem;
        
        this.setTitle("Control de Acceso de Estacionamiento");
        this.setLocationRelativeTo(null); 
        initializeGuardStatus();
        updateParkingStatus();
    }
    private EntryExitForm() {
        JsonDataManager dm = new JsonDataManager();
        ResidentManager rm = new ResidentManager();
        ParkingLot pl = new ParkingLot("DUMMY");
        VisitorManager vm = new VisitorManager(dm);
        EntryExitRecord eer = new EntryExitRecord();
        ParkingControlSystem pcs = new ParkingControlSystem("DUMMY-PCS", pl, rm);
        SecurityGuard sg = new SecurityGuard("DUMMY-G", "Dummy Guard", "DUMMY", "000", pcs, eer, rm, vm);
        
        new EntryExitForm(sg, pl, eer);
        throw new UnsupportedOperationException("Usa el constructor con parámetros para lanzar la aplicación.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPlate = new javax.swing.JLabel();
        txtPlate = new java.awt.TextField();
        btnRegisterEntry = new javax.swing.JButton();
        btnRegisterExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("REGISTRO ENTRADA Y SALIDA");

        lblPlate.setText("Placa:");

        btnRegisterEntry.setText("Registrar Entrada");
        btnRegisterEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterEntryActionPerformed(evt);
            }
        });

        btnRegisterExit.setText("Registrar Salida");
        btnRegisterExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterExitActionPerformed(evt);
            }
        });

        txtAreaLog.setColumns(20);
        txtAreaLog.setRows(5);
        jScrollPane1.setViewportView(txtAreaLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 52, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPlate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegisterEntry)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegisterExit)))))
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitle)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlate)
                    .addComponent(txtPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterEntry)
                    .addComponent(btnRegisterExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterEntryActionPerformed
        // TODO add your handling code here:
                handleEntryRegistration(evt);
    }//GEN-LAST:event_btnRegisterEntryActionPerformed

    private void btnRegisterExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterExitActionPerformed
        // TODO add your handling code here:
                handleExitRegistration(evt);
    }//GEN-LAST:event_btnRegisterExitActionPerformed
    private void initializeGuardStatus() {
        if (!this.guard.isOnDuty()) {
            this.guard.setOnDuty(true);
            log(" Guardia " + guard.getName() + " ha entrado en servicio.");
        } else {
            log(" Guardia " + guard.getName() + " ya estaba en servicio.");
        }
    }

    private void handleEntryRegistration(java.awt.event.ActionEvent event) {
        String plate = txtPlate.getText().trim().toUpperCase();
        
        if (plate.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la placa del vehículo.", "Error de Entrada", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        log("\n==================================");
        log("PROCESANDO INGRESO: " + plate);

        ParkingSpaceLibrary existingSpace = parkingLot.findSpaceByVehicle(plate);
        if (existingSpace != null) {
            log("ADVERTENCIA: Vehículo ya ocupa el espacio " + existingSpace.getSpaceId());
            JOptionPane.showMessageDialog(this, 
                    "El vehículo " + plate + " ya está registrado y ocupa el espacio " + existingSpace.getSpaceId() + ". Salida primero.", 
                    "Error: Vehículo ya Estacionado", JOptionPane.WARNING_MESSAGE);
            txtPlate.setText("");
            return;
        }
        
        this.guard.registerEntry(plate, new Date()); 
        
        log("--- REGISTRO DE ENTRADA FINALIZADO ---");
        updateParkingStatus();
        txtPlate.setText("");
    }
    
    private void handleExitRegistration(java.awt.event.ActionEvent event) {
        String plate = txtPlate.getText().trim().toUpperCase();
        
        if (plate.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la placa del vehículo.", "Error de Salida", JOptionPane.ERROR_MESSAGE);
            return;
        }

        log("\n==================================");
        log("PROCESANDO SALIDA: " + plate);
        
        ParkingSpaceLibrary occupiedSpace = parkingLot.findSpaceByVehicle(plate);
        if (occupiedSpace == null) {
            log("ERROR: Vehículo " + plate + " no encontrado en el estacionamiento.");
            JOptionPane.showMessageDialog(this, "El vehículo " + plate + " no está registrado como estacionado.", 
                                          "Error de Salida", JOptionPane.WARNING_MESSAGE);
            txtPlate.setText("");
            return;
        }

        log("Vehículo encontrado en espacio: " + occupiedSpace.getSpaceId());

        this.guard.registerExit(plate, new Date());
        
        log("--- REGISTRO DE SALIDA FINALIZADO ---");
        updateParkingStatus();
        txtPlate.setText("");
    }

    private void log(String message) {
        txtAreaLog.append(message + "\n");
        txtAreaLog.setCaretPosition(txtAreaLog.getDocument().getLength());
    }

    private void updateParkingStatus() {
        int available = parkingLot.getAvailableSpaces();
        int total = parkingLot.getTotalSpaces();
        int occupied = total - available;
        
        log("\n--- RESUMEN DE PARQUEO ---");
        log("Total de espacios: " + total);
        log("Disponibles: " + available);
        log("Ocupados: " + occupied);
        log("--------------------------\n");
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        JsonDataManager dataManager = new JsonDataManager();
        ResidentManager residentManager = new ResidentManager();
        ParkingLot parkingLot = new ParkingLot("MainLot");
        VisitorManager visitorManager = new VisitorManager(dataManager);
        EntryExitRecord logbook = new EntryExitRecord();
        
        ParkingControlSystem controlSystem = new ParkingControlSystem("PCS-01", parkingLot, residentManager);

        SecurityGuard guard = new SecurityGuard(
            "GUARD-01",
            "Juan Perez",
            "DIA",
            "555-1234",
            controlSystem,
            logbook,
            residentManager,
            visitorManager
        );
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntryExitForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EntryExitForm form = new EntryExitForm(guard, parkingLot, logbook);
                form.setVisible(true);

                form.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                        System.out.println("\nGuardando datos al cerrar...");
                        parkingLot.saveToJson(); 
                        visitorManager.saveVisitors();
                        guard.setOnDuty(false);
                        System.exit(0);
                    }
                });
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegisterEntry;
    private javax.swing.JButton btnRegisterExit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPlate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtAreaLog;
    private java.awt.TextField txtPlate;
    // End of variables declaration//GEN-END:variables
}
