package view;
import model.Resident;
import model.ResidentManager;
import model.ParkingLot; 
import model.Vehicles;
import javax.swing.*;

/**
 *
 * @author Emily Calle, @ESPE
 */
public class ResidentRegistrationFrm extends javax.swing.JFrame {

    /**
     * Creates new form ResidentRegistrationFrm
     */
    
    
    private ResidentManager residentManager;
    private ParkingLot parkingLot;

    
    public ResidentRegistrationFrm() {
    this.residentManager = new ResidentManager();
    this.parkingLot = new ParkingLot("MainLot");

    initComponents();
    setupListeners();

}
    
    private void registerAndAssign() {
    if (residentManager == null || parkingLot == null) {
        JOptionPane.showMessageDialog(this, "Error de Inicialización: Los Managers no fueron inyectados.", "Error Fatal", JOptionPane.ERROR_MESSAGE);
        return; 
    }
    
    String residentID = txtResidentID.getText().trim().toUpperCase();
    String name = txtName.getText().trim();
    String apartment = txtApartment.getText().trim();
    String email = txtEmail.getText().trim();
    String phone = txtPhone.getText().trim();
    String plate = txtPlate.getText().trim().toUpperCase();
    String color = txtColor.getText().trim();
    String model = txtModel.getText().trim();
    
    String selectedType = (String) cmbUserType.getSelectedItem();
    String assignedSpace = txtAssignedSpace.getText().trim().toUpperCase(); 
    
    txtaOutput.setText("Iniciando registro...");

    if (residentID.isEmpty() || name.isEmpty() || apartment.isEmpty() || plate.isEmpty() || color.isEmpty() || model.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe completar todos los campos del Residente y Vehículo.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
        txtaOutput.append("\nRegistro Cancelado: Faltan datos.");
        return;
    }

    if (residentManager.findResidentById(residentID) != null) {
        JOptionPane.showMessageDialog(this, "ERROR: ID de Residente ya existe.", "Error de Duplicidad", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    Vehicles checkVehicle = residentManager.findVehicleByPlate(plate);
    if (checkVehicle != null) {
        JOptionPane.showMessageDialog(this, "ERROR: La Placa " + plate + " ya está registrada en el sistema por el residente " + checkVehicle.getOwnerId() + ".", "Error de Duplicidad", JOptionPane.ERROR_MESSAGE);
        return;
    }

    Vehicles newVehicle = new Vehicles(plate, color, model, residentID);
    if (!newVehicle.validatePlate()) { 
        JOptionPane.showMessageDialog(this, "ERROR: Formato de placa inválido.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    Resident newResident;
    boolean isAssigned = selectedType.equals("ASIGNADO");

    if (isAssigned) {
        if (assignedSpace.isEmpty() || !parkingLot.spaceExists(assignedSpace)) {
            JOptionPane.showMessageDialog(this, "ERROR: Espacio asignado no puede estar vacío o no existe en el parqueo.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
            return;
        }
        newResident = new Resident(residentID, name, apartment, email, phone, assignedSpace);
    } else {
        newResident = new Resident(residentID, name, apartment, email, phone);
    }

    try {
        newResident.addVehicle(newVehicle);
        
        if (residentManager.addResident(newResident)) {
            String output = " Registro Exitoso:\n";
            
            if (isAssigned) {
                boolean assigned = parkingLot.assignSpaceToVehicle(assignedSpace, plate, newResident.getUserType().toString());
                if (assigned) {
                    output += "Espacio " + assignedSpace + " ocupado con éxito.";
                } else {
                    output += "️ Advertencia: No se pudo ocupar el espacio " + assignedSpace + " (podría estar ya ocupado).";
                }
            }

            txtaOutput.setText(output);
            JOptionPane.showMessageDialog(this, 
                "Residente " + name + " (Tipo: " + selectedType + ") registrado con éxito.", 
                "Registro Completo", JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose(); 
        } else {
            txtaOutput.append("\nRegistro fallido en el Manager (posiblemente ID duplicado en el manager).");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error inesperado al guardar: " + e.getMessage(), 
            "Error de Sistema", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTittle = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtResidentID = new java.awt.TextField();
        lblName = new javax.swing.JLabel();
        txtName = new java.awt.TextField();
        lblApartment = new javax.swing.JLabel();
        txtApartment = new java.awt.TextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new java.awt.TextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new java.awt.TextField();
        lblUserType = new javax.swing.JLabel();
        cmbUserType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        txtPlate = new java.awt.TextField();
        label1 = new java.awt.Label();
        txtColor = new java.awt.TextField();
        label3 = new java.awt.Label();
        btnRegister = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        label4 = new java.awt.Label();
        txtAssignedSpace = new java.awt.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaOutput = new javax.swing.JTextArea();
        txtModel = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTittle.setText("DATOS DEL RESIDENTE");

        lblID.setText("ID (Cédula):");

        lblName.setText("Nombre Completo:");

        lblApartment.setText("No. Apartamento:");

        lblEmail.setText("Email:");

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        lblPhone.setText("Celular:");

        lblUserType.setText("Tipo de Usuario:");

        cmbUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rotatorio", "Asignado" }));
        cmbUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUserTypeActionPerformed(evt);
            }
        });

        jLabel1.setText("DATOS DEL VEHÍCULO");

        label2.setText("Placa:");

        label1.setText("Color:");

        label3.setText("Modelo / Marca:");

        btnRegister.setText("Registrar");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        label4.setText("Espacio Asignado:");

        txtAssignedSpace.setEnabled(false);

        txtaOutput.setColumns(20);
        txtaOutput.setRows(5);
        jScrollPane1.setViewportView(txtaOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(lblMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID)
                    .addComponent(lblName)
                    .addComponent(lblApartment)
                    .addComponent(lblEmail)
                    .addComponent(lblPhone)
                    .addComponent(lblUserType)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTittle)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtResidentID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtApartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(145, 145, 145))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtModel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                .addComponent(txtPlate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtColor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtAssignedSpace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(140, 140, 140))))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(btnRegister)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTittle)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblID)
                    .addComponent(txtResidentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblApartment)
                    .addComponent(txtApartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserType)
                    .addComponent(cmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAssignedSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(lblMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setupListeners() {
      
    }
    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        registerAndAssign();


    }//GEN-LAST:event_btnRegisterActionPerformed

    private void cmbUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUserTypeActionPerformed
        // TODO add your handling code here:
        boolean isAssigned = "ASIGNADO".equals(cmbUserType.getSelectedItem()); // Nota: Usa "ASIGNADO" o "Asignado" según tu JComboBox
        txtAssignedSpace.setEnabled(isAssigned);
        if (!isAssigned) {
        txtAssignedSpace.setText("");
    }
    
    }//GEN-LAST:event_cmbUserTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResidentRegistrationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResidentRegistrationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResidentRegistrationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResidentRegistrationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResidentRegistrationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResidentRegistrationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResidentRegistrationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResidentRegistrationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new ResidentRegistrationFrm().setVisible(true);
        });
      
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cmbUserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private javax.swing.JLabel lblApartment;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JLabel lblUserType;
    private java.awt.TextField txtApartment;
    private java.awt.TextField txtAssignedSpace;
    private java.awt.TextField txtColor;
    private java.awt.TextField txtEmail;
    private java.awt.TextField txtModel;
    private java.awt.TextField txtName;
    private java.awt.TextField txtPhone;
    private java.awt.TextField txtPlate;
    private java.awt.TextField txtResidentID;
    private javax.swing.JTextArea txtaOutput;
    // End of variables declaration//GEN-END:variables

}
