package ec.edu.espe.parkinglotgui.view;

import java.util.List;
import org.bson.Document;

/**
 *
 * @author T.A.P. (The Art of Programming), @ESPE
 */
public class FrmAddVehicle extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAddVehicle.class.getName());
    private List<Document> vehicleList;

    private String residentId;

    /**
     * Creates new form FrmAddVehicle
     */
    public FrmAddVehicle() {
        initComponents();
        initPlaceholders();
        clearErrorLabels();
        setAppIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtVehicleLicensePlate = new javax.swing.JTextField();
        txtVehicleColor = new javax.swing.JTextField();
        txtVehicleModel = new javax.swing.JTextField();
        lblErrorMessageOnBoard = new javax.swing.JLabel();
        lblColorErrorMessage = new javax.swing.JLabel();
        lblVehicleModelErrorMessage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnSaveVehicle = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(15, 54, 83));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AGREGAR VEHÍCULO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Placa:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Color:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Modelo:");

        txtVehicleLicensePlate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVehicleLicensePlateFocusGained(evt);
            }
        });
        txtVehicleLicensePlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleLicensePlateActionPerformed(evt);
            }
        });

        txtVehicleColor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVehicleColorFocusGained(evt);
            }
        });
        txtVehicleColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleColorActionPerformed(evt);
            }
        });

        txtVehicleModel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVehicleModelFocusGained(evt);
            }
        });
        txtVehicleModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleModelActionPerformed(evt);
            }
        });

        lblErrorMessageOnBoard.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        lblColorErrorMessage.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        lblVehicleModelErrorMessage.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblErrorMessageOnBoard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtVehicleLicensePlate)
                    .addComponent(txtVehicleColor)
                    .addComponent(txtVehicleModel)
                    .addComponent(lblColorErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVehicleModelErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtVehicleLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorMessageOnBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtVehicleColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblColorErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtVehicleModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVehicleModelErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnSaveVehicle.setText("Guardar");
        btnSaveVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveVehicleActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnSaveVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveVehicle)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtVehicleLicensePlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleLicensePlateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleLicensePlateActionPerformed

    private void txtVehicleColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleColorActionPerformed

    private void txtVehicleModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleModelActionPerformed

    private void btnSaveVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveVehicleActionPerformed
        // TODO add your handling code here:
        String plate = txtVehicleLicensePlate.getText().trim().toUpperCase();
        String color = txtVehicleColor.getText().trim();
        String model = txtVehicleModel.getText().trim();

        if (!plate.matches("^[A-Z]{3}-\\d{4}$")) return;
        if (color.isEmpty() || model.isEmpty()) return;

        for (Document v : vehicleList) {
            if (plate.equals(v.getString("plate"))) return;
        }

        Document vehicle = new Document()
            .append("plate", plate)
            .append("color", color)
            .append("model", model)
            .append("isParked", false);

        vehicleList.add(vehicle);
        this.dispose();
    }//GEN-LAST:event_btnSaveVehicleActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        java.awt.Window[] windows = java.awt.Window.getWindows();
        for (java.awt.Window window : windows) {
            if (window instanceof FrmResident) {
                window.setEnabled(true); 
                window.toFront();       
                break;
            }
        }
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtVehicleLicensePlateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleLicensePlateFocusGained
        // TODO add your handling code here:
        if (txtVehicleLicensePlate.getText().equals("ABC-1234")) {
            txtVehicleLicensePlate.setText("");
            txtVehicleLicensePlate.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtVehicleLicensePlateFocusGained

    private void txtVehicleColorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleColorFocusGained
        // TODO add your handling code here:
        if (txtVehicleColor.getText().equals("Rojo")) {
            txtVehicleColor.setText("");
            txtVehicleColor.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtVehicleColorFocusGained

    private void txtVehicleModelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVehicleModelFocusGained
        // TODO add your handling code here:
        if (txtVehicleModel.getText().equals("Toyota Corolla")) {
            txtVehicleModel.setText("");
            txtVehicleModel.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_txtVehicleModelFocusGained
    
    private void clearErrorLabels() {
        lblErrorMessageOnBoard.setText("");
        lblColorErrorMessage.setText("");
        lblVehicleModelErrorMessage.setText("");
    }
    
    private void initPlaceholders() {
        txtVehicleLicensePlate.setText("ABC-1234");
        txtVehicleColor.setText("Rojo");
        txtVehicleModel.setText("Toyota Corolla");

        txtVehicleLicensePlate.setForeground(java.awt.Color.GRAY);
        txtVehicleColor.setForeground(java.awt.Color.GRAY);
        txtVehicleModel.setForeground(java.awt.Color.GRAY);
    }
    
    private void returnToResident() {
        FrmResident frmResident = new FrmResident();
        frmResident.setVisible(true);
        this.dispose();
    }
    
    private void setAppIcon() {
        java.net.URL iconURL = getClass().getResource("/images/logo.png");
        if (iconURL != null) {
            setIconImage(new javax.swing.ImageIcon(iconURL).getImage());
        }
    }
    
    public void setResidentId(String residentId) {
        this.residentId = residentId;
    }
    
    public void setVehicleList(List<Document> vehicleList) {
        this.vehicleList = vehicleList;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAddVehicle().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSaveVehicle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblColorErrorMessage;
    private javax.swing.JLabel lblErrorMessageOnBoard;
    private javax.swing.JLabel lblVehicleModelErrorMessage;
    private javax.swing.JTextField txtVehicleColor;
    private javax.swing.JTextField txtVehicleLicensePlate;
    private javax.swing.JTextField txtVehicleModel;
    // End of variables declaration//GEN-END:variables
}