package ec.edu.espe.parkinglotgui.view;

import ec.edu.espe.parkinglotgui.controller.ParkingSpaceController;
import ec.edu.espe.parkinglotgui.controller.VehicleEntryController;
import java.awt.Color;

/**
 *
 * @author T.A.P. (The Art of Programming), @ESPE
 */
public class FrmEntryVehicle extends javax.swing.JFrame {

    /**
     * Creates new form FrmEntry
     */
    public FrmEntryVehicle() {
        initComponents();
        loadAvailableSpaces();
        setAppIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSpaces = new javax.swing.JTable();
        txtParkingSpace = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        txtLicensePlate = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnRegisterEntry = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemReturnMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(15, 54, 83));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO DE ENTRADA DE VEHÍCULO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(147, 147, 147))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Placa del Vehículo:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Espacio de parqueadero:");

        tblSpaces.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tblSpaces.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Bloque", "Sección", "ID"
            }
        ));
        tblSpaces.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSpacesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSpaces);

        txtParkingSpace.setForeground(new java.awt.Color(153, 153, 153));
        txtParkingSpace.setText("AZU-A-01");
        txtParkingSpace.setToolTipText("<html><b>Formato de Espacio de Parqueadero:</b><br>• 3 Letras <br>• Guión (-)<br>• Una letra (Depende del bloque en el que se encuentre)<br>• Guión (-)<br>• Dos numeros<br><i>Ejemplo: AZU-A-01</i></html>");
        txtParkingSpace.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtParkingSpaceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtParkingSpaceFocusLost(evt);
            }
        });
        txtParkingSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParkingSpaceActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Espacios Disponibles");

        txtLicensePlate.setForeground(new java.awt.Color(153, 153, 153));
        txtLicensePlate.setText("ABC-1234");
        txtLicensePlate.setToolTipText("<html><b>Formato de Placa:</b><br>• 3 letras<br>• Guión (-)<br>• 4 números<br><i>Ejemplo: ABC-1234</i></html>");
        txtLicensePlate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLicensePlateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLicensePlateFocusLost(evt);
            }
        });
        txtLicensePlate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtLicensePlateMouseEntered(evt);
            }
        });
        txtLicensePlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicensePlateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtParkingSpace, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(txtLicensePlate)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(139, 139, 139))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtParkingSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(lblMessage)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnRegisterEntry.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnRegisterEntry.setText("Registrar");
        btnRegisterEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterEntryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(btnRegisterEntry)
                .addContainerGap(278, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegisterEntry)
                .addContainerGap())
        );

        jMenu1.setText("Sistema");

        itemReturnMenu.setText("Regresar al menu ");
        itemReturnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReturnMenuActionPerformed(evt);
            }
        });
        jMenu1.add(itemReturnMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadAvailableSpaces() {
        try {
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblSpaces.getModel();

            model.setRowCount(0);

            ParkingSpaceController controller = new ParkingSpaceController();
            java.util.List<org.bson.Document> spaces = controller.getAvailableSpacesDetails();

            if (spaces.isEmpty()) {
                model.addRow(new Object[]{"---", "---", "NO HAY ESPACIOS DISPONIBLES"});
            } else {
                for (org.bson.Document space : spaces) {
                    String block = space.getString("block");
                    String section = space.getString("section");
                    String id = space.getString("id");

                    model.addRow(new Object[]{block, section, id});
                }
            }

        } catch (Exception e) {
            System.err.println("Error cargando espacios: " + e.getMessage());
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblSpaces.getModel();
            model.addRow(new Object[]{"ERROR", "ERROR", "ERROR AL CARGAR"});
        }
    }

    private void btnRegisterEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterEntryActionPerformed

        String licensePlate = txtLicensePlate.getText().trim().toUpperCase();
        String spaceId = txtParkingSpace.getText().trim();

        if (licensePlate.isEmpty() || spaceId.isEmpty()) {
            lblMessage.setText("ERROR: Seleccione un espacio e ingrese la placa.");
            lblMessage.setForeground(java.awt.Color.RED);
            return;
        }

        if (!licensePlate.matches("^[A-Z]{3}-\\d{4}$")) {
            lblMessage.setText("ERROR: Formato de placa inválido (ABC-1234).");
            lblMessage.setForeground(java.awt.Color.RED);
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Registrar entrada de " + licensePlate + " en espacio " + spaceId + "?",
                "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            VehicleEntryController entryController = new VehicleEntryController();

            boolean success = entryController.registerEntry(licensePlate, spaceId);

            if (success) {
                lblMessage.setText("¡ENTRADA REGISTRADA!");
                lblMessage.setForeground(new java.awt.Color(0, 100, 0));

                txtLicensePlate.setText("");
                txtParkingSpace.setText("");

                loadAvailableSpaces();
            } else {
                lblMessage.setText("ERROR: No se pudo registrar. Verifique si el auto ya entró.");
                lblMessage.setForeground(java.awt.Color.RED);
            }
        }

    }//GEN-LAST:event_btnRegisterEntryActionPerformed

    private void itemReturnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReturnMenuActionPerformed
        FrmSecurityGuardMenu frmSecurityGuardMenu = new FrmSecurityGuardMenu();
        frmSecurityGuardMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemReturnMenuActionPerformed

    private void tblSpacesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSpacesMouseClicked
        int fila = tblSpaces.getSelectedRow();
        if (fila != -1) {
            String idSeleccionado = tblSpaces.getValueAt(fila, 2).toString();
            txtParkingSpace.setText(idSeleccionado);
            lblMessage.setText("Espacio seleccionado: " + idSeleccionado);
            lblMessage.setForeground(java.awt.Color.BLUE);
        }
    }//GEN-LAST:event_tblSpacesMouseClicked

    private void txtParkingSpaceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtParkingSpaceFocusGained
        if (txtParkingSpace.getText().equals("AZU-A-01")) {
            txtParkingSpace.setText("");
            txtParkingSpace.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtParkingSpaceFocusGained

    private void txtParkingSpaceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtParkingSpaceFocusLost
        if (txtParkingSpace.getText().isEmpty()) {
            txtParkingSpace.setText("AZU-A-01");
            txtParkingSpace.setForeground(new Color(153, 153, 153)); 
        }
    }//GEN-LAST:event_txtParkingSpaceFocusLost

    private void txtParkingSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParkingSpaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtParkingSpaceActionPerformed

    private void txtLicensePlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicensePlateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicensePlateActionPerformed

    private void txtLicensePlateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLicensePlateFocusGained
        if (txtLicensePlate.getText().equals("ABC-1234")) {
            txtLicensePlate.setText("");
            txtLicensePlate.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtLicensePlateFocusGained

    private void txtLicensePlateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLicensePlateFocusLost
        if (txtLicensePlate.getText().isEmpty()) {
            txtLicensePlate.setText("ABC-1234");
            txtLicensePlate.setForeground(new Color(153, 153, 153)); 
        }
    }//GEN-LAST:event_txtLicensePlateFocusLost

    private void txtLicensePlateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLicensePlateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicensePlateMouseEntered

    private void setAppIcon() {
        java.net.URL iconURL = getClass().getResource("/images/logo.png");
        if (iconURL != null) {
            setIconImage(new javax.swing.ImageIcon(iconURL).getImage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEntryVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEntryVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEntryVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEntryVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEntryVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegisterEntry;
    private javax.swing.JMenuItem itemReturnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTable tblSpaces;
    private javax.swing.JTextField txtLicensePlate;
    private javax.swing.JTextField txtParkingSpace;
    // End of variables declaration//GEN-END:variables
}
