package ec.edu.espe.parkinglotgui.view;

import ec.edu.espe.parkinglotgui.controller.ResidentController;
import ec.edu.espe.parkinglotgui.model.Resident;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author T.A.P. (The Art of Programming), @ESPE
 */
public class FrmResidentList extends javax.swing.JFrame {
    
    private final ResidentController residentController = new ResidentController();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmResidentList.class.getName());

    /**
     * Creates new form FrmResidentList
     */
    public FrmResidentList() {
        initComponents();
        loadResidentData();
        setAppIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        residentList = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listResident = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        addResident = new javax.swing.JButton();
        editResident = new javax.swing.JButton();
        deleteResident = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(15, 54, 83));

        residentList.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        residentList.setForeground(new java.awt.Color(255, 255, 255));
        residentList.setText("LISTA DE RESIDENTES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(residentList)
                .addGap(200, 200, 200))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(residentList)
                .addGap(29, 29, 29))
        );

        listResident.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "N° de Apartamento", "Celular", "¿Renta Activa?", "Placa Vehicular"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listResident);
        if (listResident.getColumnModel().getColumnCount() > 0) {
            listResident.getColumnModel().getColumn(0).setHeaderValue("ID");
            listResident.getColumnModel().getColumn(1).setHeaderValue("Nombre");
            listResident.getColumnModel().getColumn(2).setHeaderValue("N° de Apartamento");
            listResident.getColumnModel().getColumn(3).setHeaderValue("Celular");
            listResident.getColumnModel().getColumn(4).setHeaderValue("¿Renta Activa?");
            listResident.getColumnModel().getColumn(5).setHeaderValue("Placa Vehicular");
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        addResident.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        addResident.setText("Agregar");
        addResident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addResidentActionPerformed(evt);
            }
        });

        editResident.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        editResident.setText("Editar");
        editResident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editResidentActionPerformed(evt);
            }
        });

        deleteResident.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        deleteResident.setText("Eliminar");
        deleteResident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteResidentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(addResident, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(editResident, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(deleteResident, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteResident)
                    .addComponent(editResident)
                    .addComponent(addResident))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addResidentActionPerformed
        // TODO add your handling code here:
        JTextField nameField = new JTextField();
        JTextField phoneField = new JTextField();
        JTextField plateField = new JTextField();
        JCheckBox rentalCheck = new JCheckBox("Renta activa");

        String[] apartments = {"A-101","A-102","A-103","B-201","B-202","B-203","C-301","C-302","C-303","D-401","D-402","D-403"};
        JComboBox<String> aptCombo = new JComboBox<>(apartments);

        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nombre:")); panel.add(nameField);
        panel.add(new JLabel("Apartamento:")); panel.add(aptCombo);
        panel.add(new JLabel("Celular:")); panel.add(phoneField);
        panel.add(new JLabel("Placa Vehicular:")); panel.add(plateField);
        panel.add(new JLabel("Estado de Renta:")); panel.add(rentalCheck);

        int result = JOptionPane.showConfirmDialog(this, panel, "Agregar Residente", JOptionPane.OK_CANCEL_OPTION);
        if (result != JOptionPane.OK_OPTION) return;

        residentController.addResident(
                nameField.getText().trim(),
                (String) aptCombo.getSelectedItem(),
                phoneField.getText().trim(),
                plateField.getText().trim(),
                rentalCheck.isSelected()
        );

        loadResidentData();
    }//GEN-LAST:event_addResidentActionPerformed

    private void deleteResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteResidentActionPerformed
        // TODO add your handling code here:
        List<Resident> residents = residentController.getAllResidents();
        if (residents.isEmpty()) return;

        String[] options = residents.stream()
                .map(r -> r.getResidentID() + " - " + r.getName())
                .toArray(String[]::new);

        String selected = (String) JOptionPane.showInputDialog(
                this,
                "Seleccione:",
                "Eliminar",
                JOptionPane.PLAIN_MESSAGE,
                null,
                options,
                options[0]
        );

        if (selected == null) return;

        residentController.deleteResident(selected.split(" - ")[0]);
        loadResidentData();
    }//GEN-LAST:event_deleteResidentActionPerformed

    private void editResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editResidentActionPerformed
        // TODO add your handling code here:
        List<Resident> residents = residentController.getAllResidents();
        if (residents.isEmpty()) return;

        String[] options = residents.stream()
                .map(r -> r.getResidentID() + " - " + r.getName())
                .toArray(String[]::new);

        String selected = (String) JOptionPane.showInputDialog(
                this,
                "Seleccione:",
                "Editar",
                JOptionPane.PLAIN_MESSAGE,
                null,
                options,
                options[0]
        );

        if (selected == null) return;

        residentController.editResident(selected.split(" - ")[0]);
        loadResidentData();
    }//GEN-LAST:event_editResidentActionPerformed

    private void setAppIcon() {
        java.net.URL iconURL = getClass().getResource("/images/logo.png");
        if (iconURL != null) setIconImage(new ImageIcon(iconURL).getImage());
    }
    
    private void loadResidentData() {
    DefaultTableModel model = (DefaultTableModel) listResident.getModel();
    model.setRowCount(0);

    for (Resident r : residentController.getAllResidents()) {
        String plates = "";
        if (r.getVehicles() != null && !r.getVehicles().isEmpty()) {
            plates = r.getVehicles().stream()
                    .map(v -> v.getPlate())
                    .reduce((a, b) -> a + ", " + b)
                    .orElse("");
        }

        model.addRow(new Object[]{
            r.getResidentID(),
            r.getName(),
            r.getApartmentNumber(),
            r.getPhone(),
            r.getCurrentRental() != null && r.getCurrentRental().isActive(),
            plates
        });
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmResidentList().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addResident;
    private javax.swing.JButton deleteResident;
    private javax.swing.JButton editResident;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listResident;
    private javax.swing.JLabel residentList;
    // End of variables declaration//GEN-END:variables
}