package ec.edu.espe.parkinglotgui.view;

import ec.edu.espe.parkinglotgui.controller.LoginController;
import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;

/**
 *
 * @author Mateo Aymacaña, T.A.P. The Art Of Programming
 */
public class FrmTwoFactorDialog extends javax.swing.JDialog {

    private final LoginController loginController;
    private boolean verified = false;
    private javax.swing.Timer countdownTimer;
    private int secondsRemaining = 300;
    
    public FrmTwoFactorDialog(java.awt.Frame parent, LoginController loginController) {
        super(parent, true);
        this.loginController = loginController;
        initComponents();
        initCustomComponents();
    }
    
    private void initCustomComponents() {
        setLocationRelativeTo(getParent());
        
        txtTwoFactor.addActionListener(e -> verifyCode());
        
        getRootPane().registerKeyboardAction(
            e -> dispose(),
            KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
            JComponent.WHEN_IN_FOCUSED_WINDOW
        );
        
        lblTextError.setText("");
        lblTextError.setForeground(Color.RED);
        
        startCountdown();
    }
    
    private void startCountdown() {
        updateTimerLabel();
        
        countdownTimer = new javax.swing.Timer(1000, e -> {
            secondsRemaining--;
            updateTimerLabel();
            
            if (secondsRemaining <= 0) {
                countdownTimer.stop();
                lblTimer.setText("Código expirado");
                lblTimer.setForeground(Color.RED);
                btnVerify.setEnabled(false);
                lblTextError.setText("El código ha expirado. Haga clic en Reenviar.");
            }
        });
        countdownTimer.start();
    }
    
    private void updateTimerLabel() {
        if (secondsRemaining > 0) {
            int minutes = secondsRemaining / 60;
            int seconds = secondsRemaining % 60;
            lblTimer.setText(String.format("%02d:%02d", minutes, seconds));
            lblTimer.setForeground(new Color(0, 100, 0));
        }
    }
    
    private void verifyCode() {
        String code = txtTwoFactor.getText().trim();
        lblTextError.setText("");
        
        if (code.length() != 6 || !code.matches("\\d{6}")) {
            lblTextError.setText("El código debe tener 6 dígitos");
            txtTwoFactor.requestFocus();
            txtTwoFactor.selectAll();
            return;
        }
        
        if (loginController.validateTwoFactorCode(code)) {
            verified = true;
            countdownTimer.stop();
            dispose();
        } else {
            lblTextError.setText("Código incorrecto");
            txtTwoFactor.setText("");
            txtTwoFactor.requestFocus();
        }
    }
    
    private void resendCode() {
        if (loginController.sendTwoFactorCode()) {
            secondsRemaining = 300;
            countdownTimer.stop();
            startCountdown();
            
            btnVerify.setEnabled(true);
            lblTextError.setText("");
            txtTwoFactor.setText("");
            txtTwoFactor.requestFocus();
            
            lblTextError.setText("Nuevo código enviado");
            lblTextError.setForeground(new Color(0, 100, 0));
        } else {
            lblTextError.setText("Error al reenviar código");
        }
    }
    
    public boolean isVerified() {
        return verified;
    }
    
    @Override
    public void dispose() {
        if (countdownTimer != null) {
            countdownTimer.stop();
        }
        super.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTwoFactor = new javax.swing.JTextField();
        lblTimer = new javax.swing.JLabel();
        lblTextError = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnResend = new javax.swing.JButton();
        btnVerify = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(15, 54, 83));

        lblTitle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("VERIFICACIÓN DE DOS PASOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Código de 6 digitos enviado por Email:");

        txtTwoFactor.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtTwoFactor.setForeground(new java.awt.Color(153, 153, 153));
        txtTwoFactor.setText("XXXXXX");
        txtTwoFactor.setToolTipText("<html><b>Formato de Código de Verificación:</b><br>• 6 números<br>• No se permiten ingresar letras<br><i>Ejemplo: 123654</i></html>");
        txtTwoFactor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTwoFactorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTwoFactorFocusLost(evt);
            }
        });
        txtTwoFactor.addActionListener(this::txtTwoFactorActionPerformed);

        lblTextError.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTextError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTwoFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)))
                .addComponent(lblTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTwoFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTextError, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnCancel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnCancel.setText("Cancelar la verificación");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        btnResend.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnResend.setText("Solicitar un núevo codigo");
        btnResend.addActionListener(this::btnResendActionPerformed);

        btnVerify.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnVerify.setText("Validar Código");
        btnVerify.addActionListener(this::btnVerifyActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btnResend, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnVerify))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnResend)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        verifyCode();
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void btnResendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResendActionPerformed
        resendCode();
    }//GEN-LAST:event_btnResendActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtTwoFactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTwoFactorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTwoFactorActionPerformed

    private void txtTwoFactorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTwoFactorFocusGained
        if (txtTwoFactor.getText().equals("XXXXXX")) {
            txtTwoFactor.setText("");
            txtTwoFactor.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtTwoFactorFocusGained

    private void txtTwoFactorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTwoFactorFocusLost
        if (txtTwoFactor.getText().isEmpty()) {
            txtTwoFactor.setText("XXXXXX");
            txtTwoFactor.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtTwoFactorFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnResend;
    private javax.swing.JButton btnVerify;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblTextError;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtTwoFactor;
    // End of variables declaration//GEN-END:variables
}