package ec.edu.espe.parkinglotgui.view;

import ec.edu.espe.parkinglotgui.controller.BlockController;
import ec.edu.espe.parkinglotgui.controller.ZoneController;
import ec.edu.espe.parkinglotgui.model.Block;
import ec.edu.espe.parkinglotgui.model.Zone;
import javax.swing.JOptionPane;

/**
 *
 * @author Josue Carvajal, THE ART OF PROGRAMMING, @ESPE
 */

public class FrmBlockForm extends javax.swing.JDialog {
    public Block block;
    private FrmBlockList parent;
    private BlockController blockController;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmBlockForm.class.getName());

    /**
     * Creates new form FrmBlockForm
     */
    public FrmBlockForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadZones();     
    }
    public FrmBlockForm(FrmBlockList parent, Block block) {
        super(parent, true);
        initComponents();

        this.parent = parent;
        this.block = block;
        this.blockController = new BlockController();

        loadZones();

        if (block != null) {
            cmbZone.setSelectedItem(block.getZoneId());
            txtFloors.setText(String.valueOf(block.getFloorCount()));
        }
    }
    private void loadZones() {
        cmbZone.removeAllItems();

        ZoneController zoneController = new ZoneController();

        for (Zone z : zoneController.getAllZones()) {
            cmbZone.addItem(String.valueOf(z.getId()));
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbZone = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFloors = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Zona:");

        jLabel2.setText("Piso:");

        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFloors, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbZone, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addGap(84, 84, 84)
                        .addComponent(btnCancel)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbZone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFloors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (cmbZone.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Select a zone");
            return;
        }

        try {
            int zoneId = Integer.parseInt(cmbZone.getSelectedItem().toString());
            int floors = Integer.parseInt(txtFloors.getText());

            if (floors <= 0) {
                JOptionPane.showMessageDialog(this, "Floors must be greater than zero");
                return;
            }

            boolean success;

            if (block == null) {
                success = blockController.createBlock(zoneId, floors);
            } else {
                success = blockController.updateBlock(block.getId(), zoneId, floors);
            }

            if (success) {
                parent.loadBlocks();
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Could not save block");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Invalid numeric values");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbZone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtFloors;
    // End of variables declaration//GEN-END:variables
}
