package ec.edu.espe.parkinglotgui.view;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import ec.edu.espe.parkinglotgui.controller.VehicleEntryController;
import java.util.Set;
import org.bson.Document;

/**
 *
 * @author Emily Calle, @ESPE
 */
public class FrmEntryVehicle extends javax.swing.JFrame {

    /**
     * Creates new form FrmEntry
     */
    public FrmEntryVehicle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLicensePlate = new java.awt.TextField();
        btnRegisterEntry = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemReturnMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REGISTRO DE ENTRADA DE VEHÍCULO");

        jLabel2.setText("Placa del Vehículo:");

        btnRegisterEntry.setText("REGISTRAR");
        btnRegisterEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterEntryActionPerformed(evt);
            }
        });

        jMenu1.setText("Sistema");

        itemReturnMenu.setText("Regresar al menu ");
        itemReturnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReturnMenuActionPerformed(evt);
            }
        });
        jMenu1.add(itemReturnMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegisterEntry)
                            .addComponent(txtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegisterEntry)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterEntryActionPerformed
        String licensePlate = txtLicensePlate.getText().trim().toUpperCase();

        if (licensePlate.isEmpty()) {
            lblMessage.setText("ERROR: La placa no puede estar vacía.");
            lblMessage.setForeground(java.awt.Color.RED);
            txtLicensePlate.requestFocus();
            return;
        }

        if (!licensePlate.matches("^[A-Z]{3}-\\d{4}$")) {
            lblMessage.setText("ERROR: Formato inválido. Use: ABC-1234");
            lblMessage.setForeground(java.awt.Color.RED);
            txtLicensePlate.requestFocus();
            txtLicensePlate.selectAll();
            return;
        }

        VehicleEntryController entryController = new VehicleEntryController();
        if (entryController.isVehicleParked(licensePlate)) {
            JOptionPane.showMessageDialog(
                    this,
                    "El vehículo con placa " + licensePlate + " ya se encuentra estacionado.",
                    "Vehículo Ya Estacionado",
                    JOptionPane.WARNING_MESSAGE
            );
            lblMessage.setText("ERROR: El vehículo ya está estacionado.");
            lblMessage.setForeground(java.awt.Color.RED);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro que desea registrar la ENTRADA del vehículo?\n\n"
                + "Placa: " + licensePlate,
                "Confirmar Registro de ENTRADA",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirm != JOptionPane.YES_OPTION) {
            lblMessage.setText("Registro de entrada cancelado.");
            lblMessage.setForeground(java.awt.Color.RED);
            txtLicensePlate.setText("");
            txtLicensePlate.requestFocusInWindow();
            
            return;
        }

        boolean success = entryController.registerEntry(licensePlate);

        if (success) {
            lblMessage.setText("ENTRADA de " + licensePlate + " registrada con éxito.");
            lblMessage.setForeground(new java.awt.Color(0, 100, 0));
            txtLicensePlate.setText("");
            txtLicensePlate.requestFocus();
        } else {
            lblMessage.setText("ERROR: No se pudo registrar la entrada.");
            lblMessage.setForeground(java.awt.Color.RED);
        }
    }//GEN-LAST:event_btnRegisterEntryActionPerformed

    private void itemReturnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReturnMenuActionPerformed
        FrmSecurityGuardMenu frmSecurityGuardMenu = new FrmSecurityGuardMenu();
        frmSecurityGuardMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemReturnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEntryVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEntryVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEntryVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEntryVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEntryVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegisterEntry;
    private javax.swing.JMenuItem itemReturnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblMessage;
    private java.awt.TextField txtLicensePlate;
    // End of variables declaration//GEN-END:variables
}
