package ec.edu.espe.parkinglotgui.view;

import ec.edu.espe.parkinglotgui.controller.LoginController;
import java.awt.Color;
import java.awt.event.KeyEvent;
import ec.edu.espe.parkinglotgui.utils.FrameBlocker;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author T.A.P. (The Art of Programming), @ESPE
 */
public class FrmLogin extends javax.swing.JFrame {

    private LoginController loginController;
    private String currentUsername;
    private String currentUserType;

    public FrmLogin() {
        initComponents();
        setAppIcon();
        FrameBlocker.blockFrameControls(this, false);

        cmbUserType.removeAllItems();
        cmbUserType.addItem("Seleccionar tipo...");
        cmbUserType.addItem("Guardia de seguridad");
        cmbUserType.addItem("Residente");

        loginController = new LoginController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new java.awt.Label();
        btnLogin = new javax.swing.JButton();
        lblMessage = new java.awt.Label();
        passPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        cmbUserType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTitle.setText("INICIO DE SESIÓN");

        btnLogin.setText("Iniciar Sesión");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginKeyPressed(evt);
            }
        });

        passPassword.setText("***************");
        passPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passPasswordFocusLost(evt);
            }
        });
        passPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passPasswordMouseClicked(evt);
            }
        });
        passPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passPasswordActionPerformed(evt);
            }
        });

        jLabel1.setText("👥Tipo de usuario:");

        cmbUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUserTypeActionPerformed(evt);
            }
        });

        jLabel2.setText("🔑Contraseña:");

        jLabel3.setText("👤Usuario:");

        txtUsername.setForeground(new java.awt.Color(153, 153, 153));
        txtUsername.setText("RES-XXX");
        txtUsername.setToolTipText("<html><b>Formato de ID:</b><br>• RES (Oblogatorio)<br>• Guión (-)<br>• 3 números<br><i>Ejemplo: RES-001</i></html>");
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });

        jMenu1.setText("Sistema");

        itemExit.setText("Salir");
        itemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExitActionPerformed(evt);
            }
        });
        jMenu1.add(itemExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(passPassword)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtUsername))
                                .addGap(14, 14, 14))
                            .addComponent(cmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtUsername.getText().trim();
        String password = new String(passPassword.getPassword());
        String userType = (String) cmbUserType.getSelectedItem();

        if (!validateInputs(username, password, userType)) {
            return;
        }

        if (!loginController.validateCredentials(username, password, userType)) {
            showError("Usuario o contraseña incorrectos");
            return;
        }

        if ("Residente".equals(userType) && loginController.requiresTwoFactorForResident()) {
            handleResident2FA(username);
        } else {
            grantAccess(username, userType);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void handleResident2FA(String username) {
        if (!loginController.sendTwoFactorCode()) {
            showError("No se pudo enviar el código de verificación. Contacte al administrador.");
            return;
        }

        FrmTwoFactorDialog dialog = new FrmTwoFactorDialog(this, loginController);
        dialog.setVisible(true);

        if (dialog.isVerified()) {
            grantAccess(username, "Residente");
        } else {
            showError("Verificación cancelada o fallida");
        }
    }

    private void grantAccess(String username, String userType) {
        lblMessage.setText("¡Autenticación exitosa!");
        lblMessage.setForeground(new Color(0, 153, 0));

        Timer timer = new Timer(1000, e -> {
            if ("Guardia de seguridad".equals(userType)) {
                openSecurityGuardMenu();
            } else if ("Residente".equals(userType)) {
                openResidentMenu(username);
            }
        });
        timer.setRepeats(false);
        timer.start();
    }

    private boolean validateInputs(String username, String password, String userType) {
        if (userType == null || userType.equals("Seleccionar tipo...")) {
            showError("Seleccione un tipo de usuario");
            return false;
        }

        if (username.isEmpty() || password.isEmpty()) {
            showError("Complete todos los campos");
            return false;
        }

        return true;
    }

    private void showError(String message) {
        lblMessage.setText("ERROR: " + message);
        lblMessage.setForeground(Color.RED);
        passPassword.setText("");
        passPassword.requestFocus();
    }

    private void openSecurityGuardMenu() {
        FrmSecurityGuardMenu frm = new FrmSecurityGuardMenu();
        frm.setVisible(true);
        this.dispose();
    }

    private void openResidentMenu(String username) {
        FrmResidentMenu frm = new FrmResidentMenu(username);
        frm.setVisible(true);
        this.dispose();
    }

    private void passPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passPasswordFocusGained
        passPassword.setText("");
    }//GEN-LAST:event_passPasswordFocusGained

    private void passPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passPasswordMouseClicked
        passPassword.setText("");
    }//GEN-LAST:event_passPasswordMouseClicked

    private void btnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnLogin.doClick();
        }
    }//GEN-LAST:event_btnLoginKeyPressed

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_itemExitActionPerformed

    private void cmbUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUserTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUserTypeActionPerformed

    private void passPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passPasswordActionPerformed

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        if (txtUsername.getText().equals("RES-XXX")) {
            txtUsername.setText("");
            txtUsername.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        if (txtUsername.getText().isEmpty()) {
            txtUsername.setText("RES-XXX");
            txtUsername.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void passPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passPasswordFocusLost
        if (passPassword.getText().isEmpty()) {
            passPassword.setText("***************");
            passPassword.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_passPasswordFocusLost

    private void setAppIcon() {
        java.net.URL iconURL = getClass().getResource("/images/logo.png");
        if (iconURL != null) {
            setIconImage(new javax.swing.ImageIcon(iconURL).getImage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbUserType;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private java.awt.Label lblMessage;
    private java.awt.Label lblTitle;
    private javax.swing.JPasswordField passPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
