package ec.edu.espe.parkinglotgui.view;

import ec.edu.espe.parkinglotgui.model.ResidentDAO;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import org.bson.Document;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author T.A.P. (The Art of Programming), @ESPE
 */
public class FrmResidentList extends javax.swing.JFrame {
    private final ResidentDAO residentDAO = new ResidentDAO();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmResidentList.class.getName());

    /**
     * Creates new form FrmResidentList
     */
    public FrmResidentList() {
        initComponents();
        loadResidentData();
        
        addResident.addActionListener(evt -> addResidentActionPerformed(evt));
        editResident.addActionListener(evt -> editResidentActionPerformed(evt));
        deleteResident.addActionListener(evt -> deleteResidentActionPerformed(evt));

    }

private void loadResidentData() {
    DefaultTableModel model = (DefaultTableModel) listResident.getModel();
    model.setRowCount(0);

    for (Document doc : residentDAO.findAll()) {
        List<String> plates = doc.getList("vehiclePlates", String.class);
        String platesStr = (plates != null) ? String.join(", ", plates) : "";

        model.addRow(new Object[]{
            doc.getString("residentID"),
            doc.getString("name"),
            doc.getString("apartmentNumber"),
            doc.getString("phone"),
            doc.getBoolean("activeRental"),
            platesStr
        });
    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        residentList = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listResident = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        addResident = new javax.swing.JButton();
        editResident = new javax.swing.JButton();
        deleteResident = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(15, 54, 83));

        residentList.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        residentList.setForeground(new java.awt.Color(255, 255, 255));
        residentList.setText("LISTA DE RESIDENTES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(residentList)
                .addGap(200, 200, 200))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(residentList)
                .addGap(29, 29, 29))
        );

        listResident.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "N° de Apartamento", "Celular", "¿Renta Activa?", "Placa Vehicular"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listResident);
        if (listResident.getColumnModel().getColumnCount() > 0) {
            listResident.getColumnModel().getColumn(0).setHeaderValue("ID");
            listResident.getColumnModel().getColumn(1).setHeaderValue("Nombre");
            listResident.getColumnModel().getColumn(2).setHeaderValue("N° de Apartamento");
            listResident.getColumnModel().getColumn(3).setHeaderValue("Celular");
            listResident.getColumnModel().getColumn(4).setHeaderValue("¿Renta Activa?");
            listResident.getColumnModel().getColumn(5).setHeaderValue("Placa Vehicular");
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        addResident.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        addResident.setText("Agregar");
        addResident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addResidentActionPerformed(evt);
            }
        });

        editResident.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        editResident.setText("Editar");
        editResident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editResidentActionPerformed(evt);
            }
        });

        deleteResident.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        deleteResident.setText("Eliminar");
        deleteResident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteResidentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(addResident, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(editResident, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(deleteResident, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteResident)
                    .addComponent(editResident)
                    .addComponent(addResident))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addResidentActionPerformed
        // TODO add your handling code here:

        JTextField nameField = new JTextField();
        JTextField phoneField = new JTextField();
        JTextField plateField = new JTextField();
        JCheckBox rentalCheck = new JCheckBox("Renta activa");

        String[] apartments = {"A-101","A-102","A-103","B-201","B-202","B-203","C-301","C-302","C-303","D-401","D-402","D-403"};
        JComboBox<String> aptCombo = new JComboBox<>(apartments);

        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nombre:")); panel.add(nameField);
        panel.add(new JLabel("Apartamento:")); panel.add(aptCombo);
        panel.add(new JLabel("Celular:")); panel.add(phoneField);
        panel.add(new JLabel("Placa Vehicular:")); panel.add(plateField);
        panel.add(new JLabel("Estado de Renta:")); panel.add(rentalCheck);

        int result = JOptionPane.showConfirmDialog(
                this,
                panel,
                "Agregar Residente",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (result != JOptionPane.OK_OPTION) return;

        String name = nameField.getText().trim();
        String apt = (String) aptCombo.getSelectedItem();
        String phone = phoneField.getText().trim();
        String plate = plateField.getText().trim();
        boolean activeRental = rentalCheck.isSelected();

        if (name.isEmpty() || apt == null || phone.isEmpty() || plate.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos.");
            return;
        }

        if (!name.matches("[a-zA-Z\\s]+")) {
            JOptionPane.showMessageDialog(this, "Nombre solo puede contener letras y espacios.");
            return;
        }

        if (!phone.matches("09\\d{8}")) {
            JOptionPane.showMessageDialog(this, "Celular debe tener 10 dígitos y comenzar con 09.");
            return;
        }

        if (!plate.matches("[A-Z]{3}-\\d{4}")) {
            JOptionPane.showMessageDialog(this, "Placa debe tener el formato ABC-1234.");
            return;
        }

        long count = residentDAO.count() + 1;
        String newID = String.format("RES-%03d", count);

        Document doc = new Document()
                .append("residentID", newID)
                .append("name", name)
                .append("apartmentNumber", apt)
                .append("phone", phone)
                .append("activeRental", activeRental)
                .append("vehiclePlates", List.of(plate));

        residentDAO.insert(doc);
        loadResidentData();
        JOptionPane.showMessageDialog(this, "Residente agregado correctamente con ID: " + newID);


    }//GEN-LAST:event_addResidentActionPerformed

    private void deleteResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteResidentActionPerformed
        // TODO add your handling code here:

        List<Document> residents = residentDAO.findAll();
        if (residents.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay residentes registrados.");
            return;
        }

        String[] residentOptions = residents.stream()
                .map(r -> r.getString("residentID") + " - " + r.getString("name"))
                .toArray(String[]::new);

        String selected = (String) javax.swing.JOptionPane.showInputDialog(
                this,
                "Seleccione el residente a eliminar:",
                "Eliminar Residente",
                javax.swing.JOptionPane.PLAIN_MESSAGE,
                null,
                residentOptions,
                residentOptions[0]
        );

        if (selected == null) return;

        String residentID = selected.split(" - ")[0];

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de eliminar al residente con ID: " + residentID + "?",
                "Confirmar eliminación",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

        residentDAO.deleteById(residentID);
        loadResidentData();
        javax.swing.JOptionPane.showMessageDialog(this, "Residente eliminado correctamente");

    }//GEN-LAST:event_deleteResidentActionPerformed

    private void editResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editResidentActionPerformed
        // TODO add your handling code here:

        List<Document> residents = residentDAO.findAll();
        if (residents.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay residentes registrados.");
            return;
        }

        String[] residentOptions = residents.stream()
                .map(r -> r.getString("residentID") + " - " + r.getString("name"))
                .toArray(String[]::new);

        String selected = (String) javax.swing.JOptionPane.showInputDialog(
                this,
                "Seleccione el residente a editar:",
                "Editar Residente",
                javax.swing.JOptionPane.PLAIN_MESSAGE,
                null,
                residentOptions,
                residentOptions[0]
        );

        if (selected == null) return;

        String residentID = selected.split(" - ")[0];
        Document resident = residentDAO.findByResidentID(residentID);

        String originalName = resident.getString("name");
        String originalApt = resident.getString("apartmentNumber");
        String originalPhone = resident.getString("phone");
        Boolean originalActive = resident.getBoolean("activeRental");
        List<String> originalPlates = resident.getList("vehiclePlates", String.class);
        String originalPlatesStr = (originalPlates != null) ? String.join(", ", originalPlates) : "";

        javax.swing.JTextField nameField = new javax.swing.JTextField(originalName);
        javax.swing.JTextField aptField = new javax.swing.JTextField(originalApt);
        javax.swing.JTextField phoneField = new javax.swing.JTextField(originalPhone);
        javax.swing.JTextField plateField = new javax.swing.JTextField(originalPlatesStr);
        javax.swing.JCheckBox activeCheck = new javax.swing.JCheckBox("Renta activa");
        activeCheck.setSelected(originalActive);

        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(0, 2, 5, 5));
        panel.add(new javax.swing.JLabel("Nombre:"));
        panel.add(nameField);
        panel.add(new javax.swing.JLabel("N° Apartamento:"));
        panel.add(aptField);
        panel.add(new javax.swing.JLabel("Celular:"));
        panel.add(phoneField);
        panel.add(new javax.swing.JLabel("Placas Vehiculares (separadas por coma):"));
        panel.add(plateField);
        panel.add(new javax.swing.JLabel("Estado de Renta:"));
        panel.add(activeCheck);

        int result = javax.swing.JOptionPane.showConfirmDialog(
                this,
                panel,
                "Editar Residente",
                javax.swing.JOptionPane.OK_CANCEL_OPTION,
                javax.swing.JOptionPane.PLAIN_MESSAGE
        );

        if (result != javax.swing.JOptionPane.OK_OPTION) return;

        String newName = nameField.getText().trim();
        String newApt = aptField.getText().trim();
        String newPhone = phoneField.getText().trim();
        boolean newActive = activeCheck.isSelected();
        String platesInput = plateField.getText().trim();

        if (newName.isEmpty() || newApt.isEmpty() || newPhone.isEmpty() || platesInput.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Complete todos los campos.");
            return;
        }

        List<String> platesList = java.util.Arrays.stream(platesInput.split(","))
                .map(String::trim)
                .toList();

        org.bson.Document update = new org.bson.Document()
                .append("name", newName)
                .append("apartmentNumber", newApt)
                .append("phone", newPhone)
                .append("activeRental", newActive)
                .append("vehiclePlates", platesList);

        residentDAO.update(residentID, update);
        loadResidentData();
        javax.swing.JOptionPane.showMessageDialog(this, "Residente actualizado correctamente.");

    }//GEN-LAST:event_editResidentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmResidentList().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addResident;
    private javax.swing.JButton deleteResident;
    private javax.swing.JButton editResident;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listResident;
    private javax.swing.JLabel residentList;
    // End of variables declaration//GEN-END:variables
}
