package ec.edu.espe.parkinglotgui.view;

import com.mongodb.client.MongoCollection;
import ec.edu.espe.parkinglotgui.utils.MongoDBConnection;
import ec.edu.espe.parkinglotgui.controller.ParkingSpaceController;
import ec.edu.espe.parkinglotgui.controller.ResidentController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.bson.Document;

/**
 *
 * @author T.A.P. (The Art of Programming), @ESPE
 */
public class FrmResident extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmResident.class.getName());

    /**
     * Creates new form FrmResident
     */
    public FrmResident() {
        initComponents();
        setAppIcon();
        pnlParkingSpace.setVisible(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

    addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
            int option = javax.swing.JOptionPane.showConfirmDialog(
                    FrmResident.this,
                    "¿Desea salir sin guardar el residente?",
                    "Confirmar salida",
                    javax.swing.JOptionPane.YES_NO_OPTION
            );

            if (option == javax.swing.JOptionPane.YES_OPTION) {
                dispose();
            }
        }
    });
        lblNameError.setForeground(java.awt.Color.RED);
        lblNameError.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCellphone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbUserType = new javax.swing.JComboBox<>();
        txtApartmentNumber = new javax.swing.JTextField();
        lblNameError = new javax.swing.JLabel();
        lblApartmentError = new javax.swing.JLabel();
        lblEmailError = new javax.swing.JLabel();
        lblCellphoneError = new javax.swing.JLabel();
        lblUserTypeError = new javax.swing.JLabel();
        pnlParkingSpace = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbParkingSpace = new javax.swing.JComboBox<>();
        lblParkingError = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnSaveResident = new javax.swing.JButton();
        btnAddVehicle = new javax.swing.JButton();
        btnAuthorizeVisitor = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(15, 54, 83));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO DE RESIDENTES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(16, 16, 16))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("N° de Apartamento:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setText("Teléfono:");

        txtName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtCellphone.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtCellphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCellphoneActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("Tipo de Usuario:");

        cmbUserType.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cmbUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar tipo...", "WITH_PARKING", "ROTATING" }));
        cmbUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUserTypeActionPerformed(evt);
            }
        });

        txtApartmentNumber.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtApartmentNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApartmentNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUserTypeError, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(lblCellphoneError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmailError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblApartmentError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCellphone)
                    .addComponent(txtEmail)
                    .addComponent(txtApartmentNumber)
                    .addComponent(txtName)
                    .addComponent(cmbUserType, javax.swing.GroupLayout.Alignment.TRAILING, 0, 249, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addComponent(lblNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApartmentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblApartmentError, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmailError, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCellphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCellphoneError, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUserTypeError, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setText("Espacio de Parqueadero: ");

        cmbParkingSpace.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cmbParkingSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbParkingSpaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlParkingSpaceLayout = new javax.swing.GroupLayout(pnlParkingSpace);
        pnlParkingSpace.setLayout(pnlParkingSpaceLayout);
        pnlParkingSpaceLayout.setHorizontalGroup(
            pnlParkingSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParkingSpaceLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlParkingSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblParkingError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbParkingSpace, 0, 249, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlParkingSpaceLayout.setVerticalGroup(
            pnlParkingSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParkingSpaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlParkingSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbParkingSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblParkingError, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSaveResident.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnSaveResident.setText("Guardar");
        btnSaveResident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveResidentActionPerformed(evt);
            }
        });

        btnAddVehicle.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnAddVehicle.setText("Agregar Vehículo");
        btnAddVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVehicleActionPerformed(evt);
            }
        });

        btnAuthorizeVisitor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnAuthorizeVisitor.setText("Autorizar Visitante");
        btnAuthorizeVisitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorizeVisitorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btnAddVehicle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(btnSaveResident, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAuthorizeVisitor)
                .addGap(171, 171, 171))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddVehicle)
                    .addComponent(btnSaveResident))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAuthorizeVisitor)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jMenu2.setText("Sistema");

        jMenuItem1.setText("Regresar al Menú");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlParkingSpace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlParkingSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FrmSecurityGuardMenu frmSecurityGuardMenu = new FrmSecurityGuardMenu();
        frmSecurityGuardMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:                                         
        String name = txtName.getText().trim();

        if (name.isEmpty()) {
            lblNameError.setForeground(java.awt.Color.RED);
            lblNameError.setText("El nombre es obligatorio.");
        } else if (!name.matches("^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$")) {
            lblNameError.setForeground(java.awt.Color.RED);
            lblNameError.setText("El nombre solo puede contener letras.");
        } else {
            lblNameError.setText("");
        }
    }//GEN-LAST:event_txtNameActionPerformed

    private void cmbUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUserTypeActionPerformed
        // TODO add your handling code here:                                             
        String selectedType = cmbUserType.getSelectedItem().toString();

        if ("Seleccionar tipo...".equals(selectedType)) {
            lblUserTypeError.setForeground(java.awt.Color.RED);
            lblUserTypeError.setText("Seleccione un tipo de usuario.");
        } else {
            lblUserTypeError.setText("");
        }

        cmbParkingSpace.removeAllItems();
        cmbParkingSpace.addItem("Seleccionar espacio...");

        if ("WITH_PARKING".equals(selectedType)) {
            ParkingSpaceController controller = new ParkingSpaceController();
            List<String> spaces = controller.getAvailableSpaces();

            for (String space : spaces) {
                cmbParkingSpace.addItem(space);
            }

            pnlParkingSpace.setVisible(true);
        } else {
            pnlParkingSpace.setVisible(false);
            cmbParkingSpace.setSelectedIndex(0);
        }
    }//GEN-LAST:event_cmbUserTypeActionPerformed
    
    private void cmbParkingSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbParkingSpaceActionPerformed
        // TODO add your handling code here:                                                 
        if (cmbParkingSpace.getSelectedIndex() <= 0) {
            lblParkingError.setForeground(java.awt.Color.RED);
            lblParkingError.setText("Debe seleccionar un parqueadero.");
            return;
        }

        lblParkingError.setText("");
        String selectedSpace = cmbParkingSpace.getSelectedItem().toString();
    }//GEN-LAST:event_cmbParkingSpaceActionPerformed

    private final java.util.List<org.bson.Document> vehicles = new java.util.ArrayList<>();
    private void btnAddVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVehicleActionPerformed
        // TODO add your handling code here:                                            
        JTextField txtPlate = new JTextField();
        JTextField txtColor = new JTextField();
        JTextField txtModel = new JTextField();

        Object[] message = {
            "Placa (ABC-1234):", txtPlate,
            "Color:", txtColor,
            "Modelo:", txtModel
        };

        int option = JOptionPane.showConfirmDialog(
                this,
                message,
                "Agregar vehículo",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (option != JOptionPane.OK_OPTION) {
            return;
        }

        String plate = txtPlate.getText().trim().toUpperCase();
        String color = txtColor.getText().trim();
        String model = txtModel.getText().trim();

        if (!plate.matches("^[A-Z]{3}-\\d{4}$")) {
            JOptionPane.showMessageDialog(this, "Formato de placa inválido. Ejemplo válido: ABC-1234");
            return;
        }

        if (color.isEmpty() || model.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Color y modelo son obligatorios.");
            return;
        }

        for (org.bson.Document v : vehicles) {
            if (v.getString("plate").equals(plate)) {
                JOptionPane.showMessageDialog(this, "Esta placa ya fue agregada.");
                return;
            }
        }

        org.bson.Document vehicle = new org.bson.Document()
                .append("plate", plate)
                .append("color", color)
                .append("model", model)
                .append("isParked", false);

        vehicles.add(vehicle);
    }//GEN-LAST:event_btnAddVehicleActionPerformed

    private void txtApartmentNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApartmentNumberActionPerformed
        // TODO add your handling code here:                                                    
        String apartment = txtApartmentNumber.getText().trim();

        if (apartment.isEmpty()) {
            lblApartmentError.setForeground(java.awt.Color.RED);
            lblApartmentError.setText("El número de apartamento es obligatorio.");
        } else if (!apartment.matches("^[A-Z]-\\d{3}$")) {
            lblApartmentError.setForeground(java.awt.Color.RED);
            lblApartmentError.setText("Formato inválido. Ejemplo: D-301");
        } else {
            lblApartmentError.setText("");
        }
    }//GEN-LAST:event_txtApartmentNumberActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:                                         
        String email = txtEmail.getText().trim();

        if (email.isEmpty()) {
            lblEmailError.setForeground(java.awt.Color.RED);
            lblEmailError.setText("El correo electrónico es obligatorio.");
        } else if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$")) {
            lblEmailError.setForeground(java.awt.Color.RED);
            lblEmailError.setText("Correo inválido. Ejemplo: nombre@correo.com");
        } else {
            lblEmailError.setText("");
        }
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtCellphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCellphoneActionPerformed
        // TODO add your handling code here:                                              
        String cellphone = txtCellphone.getText().trim();

        if (cellphone.isEmpty()) {
            lblCellphoneError.setForeground(java.awt.Color.RED);
            lblCellphoneError.setText("El número de celular es obligatorio.");
        } else if (!cellphone.matches("^09\\d{8}$")) {
            lblCellphoneError.setForeground(java.awt.Color.RED);
            lblCellphoneError.setText("Debe iniciar con 09 y tener 10 dígitos.");
        } else {
            lblCellphoneError.setText("");
        }
    }//GEN-LAST:event_txtCellphoneActionPerformed
    
    private final java.util.List<String> authorizedVisitors = new java.util.ArrayList<>();
    private void btnSaveResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveResidentActionPerformed
        // TODO add your handling code here: 
        String name = txtName.getText().trim();
        String apartmentNumber = txtApartmentNumber.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtCellphone.getText().trim();
        String userType = cmbUserType.getSelectedItem().toString();
        String assignedParkingSpace = cmbParkingSpace.getSelectedItem() != null 
                                      ? cmbParkingSpace.getSelectedItem().toString() 
                                      : null;

        if (name.isEmpty() || apartmentNumber.isEmpty() || email.isEmpty() || phone.isEmpty() || userType.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            return;
        }
        
        ResidentController controller = new ResidentController();

        controller.addResident(
                name,
                apartmentNumber,
                phone,
                vehicles.isEmpty() ? null : vehicles.get(0).getString("plate"),
                "WITH_PARKING".equals(userType)
        );

        JOptionPane.showMessageDialog(this, "Residente guardado correctamente");

        vehicles.clear();
        authorizedVisitors.clear();
        txtName.setText("");
        txtApartmentNumber.setText("");
        txtEmail.setText("");
        txtCellphone.setText("");
        cmbUserType.setSelectedIndex(0);
        cmbParkingSpace.setSelectedIndex(0);

    }//GEN-LAST:event_btnSaveResidentActionPerformed

    private List<String> authorizedVisitorsList = new ArrayList<>();
    private void btnAuthorizeVisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorizeVisitorActionPerformed
        // TODO add your handling code here:
        String visitorID = JOptionPane.showInputDialog(this, "Ingrese ID del visitante (formato VIS-XXX):");
        if (visitorID == null || visitorID.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se ingresó ningún ID.");
            return;
        }
        visitorID = visitorID.trim().toUpperCase();
        if (!visitorID.matches("VIS-\\d{3}")) {
            JOptionPane.showMessageDialog(this, "Formato inválido. Use VIS-XXX.");
            return;
        }
        if (authorizedVisitorsList.contains(visitorID)) {
            JOptionPane.showMessageDialog(this, "El visitante ya está autorizado.");
            return;
        }
        authorizedVisitorsList.add(visitorID);
        JOptionPane.showMessageDialog(this, "Visitante autorizado: " + visitorID);
    }//GEN-LAST:event_btnAuthorizeVisitorActionPerformed
    
    private void setAppIcon() {
        java.net.URL iconURL = getClass().getResource("/images/logo.png");
        if (iconURL != null) {
            setIconImage(new javax.swing.ImageIcon(iconURL).getImage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmResident().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVehicle;
    private javax.swing.JButton btnAuthorizeVisitor;
    private javax.swing.JButton btnSaveResident;
    private javax.swing.JComboBox<String> cmbParkingSpace;
    private javax.swing.JComboBox<String> cmbUserType;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblApartmentError;
    private javax.swing.JLabel lblCellphoneError;
    private javax.swing.JLabel lblEmailError;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblParkingError;
    private javax.swing.JLabel lblUserTypeError;
    private javax.swing.JPanel pnlParkingSpace;
    private javax.swing.JTextField txtApartmentNumber;
    private javax.swing.JTextField txtCellphone;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}