package ec.edu.espe.parkinglotgui.view;

/**
 *
 * @author Mateo Aymacaña, T.A.P. (The Art of Programming), @ESPE
 */
public class FrmSecurityGuardMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmSecurityGuardMenu.class.getName());

    /**
     * Creates new form FrmSecurityGuardMenu
     */
    public FrmSecurityGuardMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        itemReturnMenu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itemRegisterEntry = new javax.swing.JMenuItem();
        itemRegisterExit = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        itemNewVisitor = new javax.swing.JMenuItem();
        itemNewResident = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu5.setText("Configuracion");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu5.add(jMenuItem1);

        itemReturnMenu.setText("Regresar al menu principal");
        itemReturnMenu.addActionListener(this::itemReturnMenuActionPerformed);
        jMenu5.add(itemReturnMenu);

        jMenuBar1.add(jMenu5);

        jMenu1.setText("Registro de entrada y salida");

        itemRegisterEntry.setText("Registrar entrada");
        itemRegisterEntry.addActionListener(this::itemRegisterEntryActionPerformed);
        jMenu1.add(itemRegisterEntry);

        itemRegisterExit.setText("Registrar salida");
        itemRegisterExit.addActionListener(this::itemRegisterExitActionPerformed);
        jMenu1.add(itemRegisterExit);

        jMenuBar1.add(jMenu1);

        jMenu6.setText("Agregar nuevo usuario");

        itemNewVisitor.setText("Agregar nuevo vistante");
        itemNewVisitor.addActionListener(this::itemNewVisitorActionPerformed);
        jMenu6.add(itemNewVisitor);

        itemNewResident.setText("Agregar nuevo residente");
        jMenu6.add(itemNewResident);

        jMenuBar1.add(jMenu6);

        jMenu3.setText("Ver Reportes");

        jMenuItem2.setText("Reporte de Vehiculos");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Reporte de Visitantes");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Reporte de entrada y salida");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemRegisterEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegisterEntryActionPerformed
        FrmEntryVehicle frmEntryVehicle = new FrmEntryVehicle();
        frmEntryVehicle.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemRegisterEntryActionPerformed

    private void itemReturnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReturnMenuActionPerformed
        FrmLogin frmLogin = new FrmLogin();
        frmLogin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemReturnMenuActionPerformed

    private void itemRegisterExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegisterExitActionPerformed
        FrmExitVehicle frmExitVehicle = new FrmExitVehicle();
        frmExitVehicle.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemRegisterExitActionPerformed

    private void itemNewVisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNewVisitorActionPerformed
        FrmVisitor frmVisitor = new FrmVisitor();
        frmVisitor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemNewVisitorActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmVehicleList frmVehicleList = new FrmVehicleList();
        frmVehicleList.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmSecurityGuardMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemNewResident;
    private javax.swing.JMenuItem itemNewVisitor;
    private javax.swing.JMenuItem itemRegisterEntry;
    private javax.swing.JMenuItem itemRegisterExit;
    private javax.swing.JMenuItem itemReturnMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
