package ec.edu.espe.parkinglotgui.view;

import ec.edu.espe.parkinglotgui.controller.LoginController;
import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;

/**
 *
 * @author Mateo Aymacaña, T.A.P. The Art Of Programming
 */
public class FrmTwoFactorDialog extends javax.swing.JDialog {

    private final LoginController loginController;
    private boolean verified = false;
    private javax.swing.Timer countdownTimer;
    private int secondsRemaining = 300;
    
    public FrmTwoFactorDialog(java.awt.Frame parent, LoginController loginController) {
        super(parent, true);
        this.loginController = loginController;
        initComponents();
        initCustomComponents();
    }
    
    private void initCustomComponents() {
        setLocationRelativeTo(getParent());
        
        txtTwoFactor.addActionListener(e -> verifyCode());
        
        getRootPane().registerKeyboardAction(
            e -> dispose(),
            KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
            JComponent.WHEN_IN_FOCUSED_WINDOW
        );
        
        lblTextError.setText("");
        lblTextError.setForeground(Color.RED);
        
        startCountdown();
    }
    
    private void startCountdown() {
        updateTimerLabel();
        
        countdownTimer = new javax.swing.Timer(1000, e -> {
            secondsRemaining--;
            updateTimerLabel();
            
            if (secondsRemaining <= 0) {
                countdownTimer.stop();
                lblTimer.setText("Código expirado");
                lblTimer.setForeground(Color.RED);
                btnVerify.setEnabled(false);
                lblTextError.setText("El código ha expirado. Haga clic en Reenviar.");
            }
        });
        countdownTimer.start();
    }
    
    private void updateTimerLabel() {
        if (secondsRemaining > 0) {
            int minutes = secondsRemaining / 60;
            int seconds = secondsRemaining % 60;
            lblTimer.setText(String.format("%02d:%02d", minutes, seconds));
            lblTimer.setForeground(new Color(0, 100, 0));
        }
    }
    
    private void verifyCode() {
        String code = txtTwoFactor.getText().trim();
        lblTextError.setText("");
        
        if (code.length() != 6 || !code.matches("\\d{6}")) {
            lblTextError.setText("El código debe tener 6 dígitos");
            txtTwoFactor.requestFocus();
            txtTwoFactor.selectAll();
            return;
        }
        
        if (loginController.validateTwoFactorCode(code)) {
            verified = true;
            countdownTimer.stop();
            dispose();
        } else {
            lblTextError.setText("Código incorrecto");
            txtTwoFactor.setText("");
            txtTwoFactor.requestFocus();
        }
    }
    
    private void resendCode() {
        if (loginController.sendTwoFactorCode()) {
            secondsRemaining = 300;
            countdownTimer.stop();
            startCountdown();
            
            btnVerify.setEnabled(true);
            lblTextError.setText("");
            txtTwoFactor.setText("");
            txtTwoFactor.requestFocus();
            
            lblTextError.setText("Nuevo código enviado");
            lblTextError.setForeground(new Color(0, 100, 0));
        } else {
            lblTextError.setText("Error al reenviar código");
        }
    }
    
    public boolean isVerified() {
        return verified;
    }
    
    @Override
    public void dispose() {
        if (countdownTimer != null) {
            countdownTimer.stop();
        }
        super.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVerify = new javax.swing.JButton();
        btnResend = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtTwoFactor = new javax.swing.JTextField();
        lblTimer = new javax.swing.JLabel();
        lblTextError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setText("Verificación de Dos Pasos");

        jLabel2.setText("Código de 6 digitos enviado por Emial:");

        btnVerify.setText("Validar Código");
        btnVerify.addActionListener(this::btnVerifyActionPerformed);

        btnResend.setText("Solicitar un núevo codigo");
        btnResend.addActionListener(this::btnResendActionPerformed);

        btnCancel.setText("Cancelar la verificación");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        txtTwoFactor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTwoFactor.setForeground(new java.awt.Color(153, 153, 153));
        txtTwoFactor.setText("XXXXXX");
        txtTwoFactor.setToolTipText("<html><b>Formato de Código de Verificación:</b><br>• 6 números<br>• No se permiten ingresar letras<br><i>Ejemplo: 123654</i></html>");
        txtTwoFactor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTwoFactorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTwoFactorFocusLost(evt);
            }
        });
        txtTwoFactor.addActionListener(this::txtTwoFactorActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(184, 184, 184))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTextError, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(txtTwoFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(btnResend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTwoFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblTextError, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResend)
                    .addComponent(btnVerify))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        verifyCode();
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void btnResendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResendActionPerformed
        resendCode();
    }//GEN-LAST:event_btnResendActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtTwoFactorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTwoFactorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTwoFactorActionPerformed

    private void txtTwoFactorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTwoFactorFocusGained
        if (txtTwoFactor.getText().equals("XXXXXX")) {
            txtTwoFactor.setText("");
            txtTwoFactor.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_txtTwoFactorFocusGained

    private void txtTwoFactorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTwoFactorFocusLost
        if (txtTwoFactor.getText().isEmpty()) {
            txtTwoFactor.setText("XXXXXX");
            txtTwoFactor.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtTwoFactorFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnResend;
    private javax.swing.JButton btnVerify;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblTextError;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtTwoFactor;
    // End of variables declaration//GEN-END:variables
}
