package ec.edu.espe.parkinglotgui.view;

import ec.edu.espe.parkinglotgui.controller.VisitorController;
import ec.edu.espe.parkinglotgui.model.Visitor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emily Calle, @ESPE
 */
public class FrmVisitor extends javax.swing.JFrame {

    private final VisitorController visitorController;

    public FrmVisitor() {
        initComponents();
        setAppIcon();

        this.visitorController = new VisitorController();
        loadVisitorsTable();

        clearFields();
    }

    private void clearFields() {
        txtVisitorID.setText("");
        txtNameVisitor.setText("");
        txtVehiclePlate.setText("");
        txResidentID.setText("");
        chkHasPass.setSelected(false);
        cmbStatus.setSelectedIndex(0);
        txtVisitorID.setEditable(true);
    }

    private void loadVisitorsTable() {
        DefaultTableModel model = new DefaultTableModel();

        model.setColumnIdentifiers(new Object[]{
            "ID Visitante",
            "Nombre",
            "ID Residente",
            "Placa Vehículo",
            "Tiene Pase",
            "Estado"
        });
        List<Visitor> visitors = visitorController.getAllVisitors();

        for (Visitor visitor : visitors) {
            model.addRow(new Object[]{
                visitor.getVisitorID(),
                visitor.getNameVisitor(),
                visitor.getResidentID(),
                visitor.getVehiclePlate(),
                visitor.isHasPass(),
                visitor.getLibraryVisitorStatus()
            });
        }
        tblVisitors.setModel(model);
    }

    private Visitor getVisitorFromForm() {

        String visitorID = txtVisitorID.getText().trim();
        String nameVisitor = txtNameVisitor.getText().trim();
        String residentID = txResidentID.getText().trim();
        String vehiclePlate = txtVehiclePlate.getText().trim();
        boolean hasPass = chkHasPass.isSelected();

        Visitor visitor = new Visitor();

        visitor.setVisitorID(visitorID);
        visitor.setNameVisitor(nameVisitor);
        visitor.setResidentID(residentID);
        visitor.setVehiclePlate(vehiclePlate);

        visitor.setHasPass(hasPass);

        String selectedStatus = (String) cmbStatus.getSelectedItem();
        visitor.setLibraryVisitorStatus(selectedStatus);

        return visitor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVisitorID = new javax.swing.JLabel();
        txtVisitorID = new java.awt.TextField();
        lblNameVisitor = new javax.swing.JLabel();
        txtNameVisitor = new java.awt.TextField();
        lblUserID = new javax.swing.JLabel();
        txResidentID = new java.awt.TextField();
        lblVehiclePlate = new javax.swing.JLabel();
        txtVehiclePlate = new java.awt.TextField();
        chkHasPass = new javax.swing.JCheckBox();
        lblStatus = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVisitors = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemReturnMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblVisitorID.setText("ID Visitante:");

        txtVisitorID.setEditable(false);
        txtVisitorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVisitorIDActionPerformed(evt);
            }
        });

        lblNameVisitor.setText("Nombre:");

        txtNameVisitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameVisitorActionPerformed(evt);
            }
        });

        lblUserID.setText("ID Residente:");

        lblVehiclePlate.setText("Placa del Vehiculo:");

        chkHasPass.setText("Tiene Pase");

        lblStatus.setText("Estado:");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo", "Con pase", "Sin pase" }));

        btnUpdate.setText("ACTUALIZAR");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setText("GUARDAR");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("ELIMINAR");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblVisitors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Visitante", "Nombre", "ID Residente", "Placa Vehículo", "Tiene Pase", "Estado"
            }
        ));
        tblVisitors.setToolTipText("");
        tblVisitors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVisitorsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVisitors);

        jPanel1.setBackground(new java.awt.Color(15, 54, 83));

        lblTitle.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("REGISTRO DE VISITANTES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(lblTitle)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitle)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jMenu1.setText("Sistema");

        itemReturnMenu.setText("Regresar al menu");
        itemReturnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReturnMenuActionPerformed(evt);
            }
        });
        jMenu1.add(itemReturnMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)))
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNameVisitor)
                                    .addComponent(lblVisitorID)
                                    .addComponent(lblUserID)
                                    .addComponent(lblVehiclePlate)
                                    .addComponent(lblStatus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cmbStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, 154, Short.MAX_VALUE)
                                    .addComponent(txtVehiclePlate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txResidentID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNameVisitor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtVisitorID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(chkHasPass))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVisitorID)
                    .addComponent(txtVisitorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNameVisitor)
                    .addComponent(txtNameVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserID)
                    .addComponent(txResidentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVehiclePlate)
                    .addComponent(txtVehiclePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkHasPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnSave)
                    .addComponent(btnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            if (txtVisitorID.getText().isEmpty() || txtNameVisitor.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El ID Visitante y el Nombre son campos obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            String nameVisitor = txtNameVisitor.getText().trim();
            if (nameVisitor.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "El nombre del visitante no puede estar vacío.",
                        "Error de Validación",
                        JOptionPane.ERROR_MESSAGE);
                txtNameVisitor.requestFocus();
                return;
            }

            if (nameVisitor.length() < 2) {
                JOptionPane.showMessageDialog(this,
                        "El nombre debe tener al menos 2 caracteres.",
                        "Error de Validación",
                        JOptionPane.ERROR_MESSAGE);
                txtNameVisitor.requestFocus();
                txtNameVisitor.selectAll();
                return;
            }

            if (nameVisitor.matches(".*\\d.*")) {
                JOptionPane.showMessageDialog(this,
                        "El nombre no puede contener números.",
                        "Error de Validación",
                        JOptionPane.ERROR_MESSAGE);
                txtNameVisitor.requestFocus();
                txtNameVisitor.selectAll();
                return;
            }

            Visitor newVisitor = new Visitor();
            newVisitor.setVisitorID(txtVisitorID.getText());
            newVisitor.setNameVisitor(txtNameVisitor.getText());
            newVisitor.setResidentID(txResidentID.getText());
            newVisitor.setVehiclePlate(txtVehiclePlate.getText());
            newVisitor.setHasPass(chkHasPass.isSelected());
            newVisitor.setLibraryVisitorStatus((String) cmbStatus.getSelectedItem());

            visitorController.saveVisitor(newVisitor);

            loadVisitorsTable();
            clearFields();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error al guardar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            if (txtVisitorID.isEditable() || txtVisitorID.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un visitante de la tabla para actualizar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Visitor updatedVisitor = getVisitorFromForm();

            if (visitorController.updateVisitor(updatedVisitor)) {

                JOptionPane.showMessageDialog(this, "Datos del visitante actualizados correctamente.", "Actualización Completa", JOptionPane.INFORMATION_MESSAGE);

                loadVisitorsTable();
                clearFields();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al procesar la actualización: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String idToDelete = txtVisitorID.getText();

        if (txtVisitorID.isEditable() || idToDelete.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un visitante de la tabla para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de que desea eliminar al visitante con ID: " + idToDelete + "?",
                "Confirmar Eliminación",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if (visitorController.deleteVisitor(idToDelete)) {
                loadVisitorsTable();
                clearFields();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblVisitorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVisitorsMouseClicked
        int selectedRow = tblVisitors.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) tblVisitors.getModel();

            txtVisitorID.setText(model.getValueAt(selectedRow, 0).toString());
            txtNameVisitor.setText(model.getValueAt(selectedRow, 1).toString());
            txResidentID.setText(model.getValueAt(selectedRow, 2).toString());
            txtVehiclePlate.setText(model.getValueAt(selectedRow, 3).toString());
            chkHasPass.setSelected((Boolean) model.getValueAt(selectedRow, 4));
            cmbStatus.setSelectedItem(model.getValueAt(selectedRow, 5).toString());

            txtVisitorID.setEditable(false);
        }
    }//GEN-LAST:event_tblVisitorsMouseClicked

    private void itemReturnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReturnMenuActionPerformed
        FrmSecurityGuardMenu frmSecurityGuardMenu = new FrmSecurityGuardMenu();
        frmSecurityGuardMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemReturnMenuActionPerformed

    private void txtVisitorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVisitorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVisitorIDActionPerformed

    private void txtNameVisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameVisitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameVisitorActionPerformed

    private void setAppIcon() {
        java.net.URL iconURL = getClass().getResource("/images/logo.png");
        if (iconURL != null) {
            setIconImage(new javax.swing.ImageIcon(iconURL).getImage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVisitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVisitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVisitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVisitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVisitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkHasPass;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JMenuItem itemReturnMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNameVisitor;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblVehiclePlate;
    private javax.swing.JLabel lblVisitorID;
    private javax.swing.JTable tblVisitors;
    private java.awt.TextField txResidentID;
    private java.awt.TextField txtNameVisitor;
    private java.awt.TextField txtVehiclePlate;
    private java.awt.TextField txtVisitorID;
    // End of variables declaration//GEN-END:variables
}
