package ec.edu.espe.parkinglotgui.view;

import ec.edu.espe.parkinglotgui.model.VehicleDAO;
import org.bson.Document;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Arelis Samantha Bonilla Cruz, Student, @ESPE
 */
public class FrmVehicleList extends javax.swing.JFrame {
    private final VehicleDAO vehicleDAO = new VehicleDAO();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmVehicleList.class.getName());

    /**
     * Creates new form FrmVehicleList
     */
    public FrmVehicleList() {
        initComponents();
        loadVehicleData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        addVehicle = new javax.swing.JButton();
        deleteVehicle = new javax.swing.JButton();
        editVehicle = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        vehicleList = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemReturnMenu = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tittle.setFont(new java.awt.Font("Eras Demi ITC", 0, 36)); // NOI18N
        tittle.setText("Lista de Vehículos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tittle)
                .addGap(289, 289, 289))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(tittle)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        addVehicle.setText("Agregar");
        addVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVehicleActionPerformed(evt);
            }
        });

        deleteVehicle.setText("Eliminar");
        deleteVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVehicleActionPerformed(evt);
            }
        });

        editVehicle.setText("Editar");
        editVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editVehicleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(addVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171)
                .addComponent(deleteVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(editVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addVehicle)
                    .addComponent(deleteVehicle)
                    .addComponent(editVehicle))
                .addGap(22, 22, 22))
        );

        vehicleList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID de Propietario", "Nombre del Propietario", "Placa", "Color", "Modelo", "¿Parqueado?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(vehicleList);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Sistema");

        itemReturnMenu.setText("Regresar al menu");
        itemReturnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReturnMenuActionPerformed(evt);
            }
        });
        jMenu1.add(itemReturnMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVehicleActionPerformed
        // TODO add your handling code here:

        List<Document> docs = vehicleDAO.findAll();

        List<String> ownerIds = new ArrayList<>();
        List<Document> owners = new ArrayList<>();

        for (Document d : docs) {
            String ownerId = d.getString("ownerId");
            if (!ownerIds.contains(ownerId)) {
                ownerIds.add(ownerId);
                owners.add(d);
            }
        }

        String selectedOwnerId = (String) JOptionPane.showInputDialog(
                this,
                "Selecciona un propietario",
                "Eliminar Vehículo",
                JOptionPane.QUESTION_MESSAGE,
                null,
                ownerIds.toArray(),
                null
        );

        if (selectedOwnerId == null) return;

        List<String> plates = new ArrayList<>();
        for (Document d : docs) {
            if (d.getString("ownerId").equals(selectedOwnerId)) {
                plates.add(d.getString("plate"));
            }
        }

        String selectedPlate = (String) JOptionPane.showInputDialog(
                this,
                "Selecciona el vehículo",
                "Eliminar Vehículo",
                JOptionPane.QUESTION_MESSAGE,
                null,
                plates.toArray(),
                null
        );

        if (selectedPlate == null) return;

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Estás seguro de eliminar este vehículo?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) return;

        vehicleDAO.deleteByOwnerAndPlate(selectedOwnerId, selectedPlate);

        JOptionPane.showMessageDialog(this, "Vehículo eliminado correctamente");
        loadVehicleData();
    }//GEN-LAST:event_deleteVehicleActionPerformed

    private void itemReturnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReturnMenuActionPerformed
        FrmSecurityGuardMenu frmSecurityGuardMenu = new FrmSecurityGuardMenu();
        frmSecurityGuardMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemReturnMenuActionPerformed

    private void addVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVehicleActionPerformed
        // TODO add your handling code here:

        List<Document> docs = vehicleDAO.findAll();

        List<String> ownerIds = new ArrayList<>();
        List<Document> owners = new ArrayList<>();

        for (Document d : docs) {
            String ownerId = d.getString("ownerId");
            if (!ownerIds.contains(ownerId)) {
                ownerIds.add(ownerId);
                owners.add(d);
            }
        }

        String selectedOwnerId = (String) JOptionPane.showInputDialog(
                this,
                "Selecciona un propietario",
                "Agregar Vehículo",
                JOptionPane.QUESTION_MESSAGE,
                null,
                ownerIds.toArray(),
                null
        );

        if (selectedOwnerId == null) return;

        Document selectedOwner = null;
        for (Document d : owners) {
            if (d.getString("ownerId").equals(selectedOwnerId)) {
                selectedOwner = d;
                break;
            }
        }

        JTextField plateField = new JTextField();
        JTextField colorField = new JTextField();
        JTextField modelField = new JTextField();
        JCheckBox parkedCheck = new JCheckBox("¿Parqueado?");

        JPanel panel = new JPanel(new java.awt.GridLayout(0, 1));
        panel.add(new JLabel("Placa"));
        panel.add(plateField);
        panel.add(new JLabel("Color"));
        panel.add(colorField);
        panel.add(new JLabel("Modelo"));
        panel.add(modelField);
        panel.add(parkedCheck);

        int result = JOptionPane.showConfirmDialog(
                this,
                panel,
                "Datos del Vehículo",
                JOptionPane.OK_CANCEL_OPTION
        );

        if (result != JOptionPane.OK_OPTION) return;

        Document newVehicle = new Document()
                .append("ownerId", selectedOwner.getString("ownerId"))
                .append("ownerName", selectedOwner.getString("ownerName"))
                .append("plate", plateField.getText())
                .append("color", colorField.getText())
                .append("model", modelField.getText())
                .append("parked", parkedCheck.isSelected());

        vehicleDAO.insert(newVehicle);

        JOptionPane.showMessageDialog(this, "Vehículo agregado correctamente");
        loadVehicleData();
    }//GEN-LAST:event_addVehicleActionPerformed

    private void editVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editVehicleActionPerformed
        // TODO add your handling code here:

        List<Document> docs = vehicleDAO.findAll();

        List<String> ownerIds = new ArrayList<>();
        for (Document d : docs) {
            if (!ownerIds.contains(d.getString("ownerId"))) {
                ownerIds.add(d.getString("ownerId"));
            }
        }

        String selectedOwnerId = (String) JOptionPane.showInputDialog(
                this,
                "Selecciona un propietario",
                "Editar Vehículo",
                JOptionPane.QUESTION_MESSAGE,
                null,
                ownerIds.toArray(),
                null
        );

        if (selectedOwnerId == null) return;

        List<Document> vehicles = new ArrayList<>();
        List<String> plates = new ArrayList<>();

        for (Document d : docs) {
            if (d.getString("ownerId").equals(selectedOwnerId)) {
                vehicles.add(d);
                plates.add(d.getString("plate"));
            }
        }

        String selectedPlate = (String) JOptionPane.showInputDialog(
                this,
                "Selecciona el vehículo",
                "Editar Vehículo",
                JOptionPane.QUESTION_MESSAGE,
                null,
                plates.toArray(),
                null
        );

        if (selectedPlate == null) return;

        Document vehicle = null;
        for (Document d : vehicles) {
            if (d.getString("plate").equals(selectedPlate)) {
                vehicle = d;
                break;
            }
        }

        JTextField plateField = new JTextField(vehicle.getString("plate"));
        JTextField colorField = new JTextField(vehicle.getString("color"));
        JTextField modelField = new JTextField(vehicle.getString("model"));
        JCheckBox parkedCheck = new JCheckBox("¿Parqueado?", vehicle.getBoolean("parked"));

        JPanel panel = new JPanel(new java.awt.GridLayout(0, 1));
        panel.add(new JLabel("Placa"));
        panel.add(plateField);
        panel.add(new JLabel("Color"));
        panel.add(colorField);
        panel.add(new JLabel("Modelo"));
        panel.add(modelField);
        panel.add(parkedCheck);

        int result = JOptionPane.showConfirmDialog(
                this,
                panel,
                "Editar Vehículo",
                JOptionPane.OK_CANCEL_OPTION
        );

        if (result != JOptionPane.OK_OPTION) return;

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Deseas guardar los cambios?",
                "Confirmación",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) return;

        vehicleDAO.updateVehicle(
                selectedOwnerId,
                selectedPlate,
                new Document()
                        .append("plate", plateField.getText())
                        .append("color", colorField.getText())
                        .append("model", modelField.getText())
                        .append("parked", parkedCheck.isSelected())
        );

        JOptionPane.showMessageDialog(this, "Vehículo actualizado correctamente");
        loadVehicleData();
    }//GEN-LAST:event_editVehicleActionPerformed

    private void loadVehicleData() {
        DefaultTableModel model = (DefaultTableModel) vehicleList.getModel();
        model.setRowCount(0);

        List<Document> docs = vehicleDAO.findAllSortedByOwner();

        String lastOwnerId = "";

        for (Document doc : docs) {
            String ownerId = doc.getString("ownerId");
            String ownerName = doc.getString("ownerName");

            String showOwnerId = ownerId.equals(lastOwnerId) ? "" : ownerId;
            String showOwnerName = ownerId.equals(lastOwnerId) ? "" : ownerName;

            model.addRow(new Object[]{
                showOwnerId,
                showOwnerName,
                doc.getString("plate"),
                doc.getString("color"),
                doc.getString("model"),
                doc.getBoolean("parked")
            });

            lastOwnerId = ownerId;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmVehicleList().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVehicle;
    private javax.swing.JButton deleteVehicle;
    private javax.swing.JButton editVehicle;
    private javax.swing.JMenuItem itemReturnMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel tittle;
    private javax.swing.JTable vehicleList;
    // End of variables declaration//GEN-END:variables
}