
package ec.edu.espe.rentalresidentgui.view;

import ec.edu.espe.rentalresidentgui.controller.VisitorController;
import ec.edu.espe.rentalresidentgui.model.Visitor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Emily Calle, @ESPE
 */
public class FrmVisitor extends javax.swing.JFrame {

    private final VisitorController visitorController;
    public FrmVisitor() {
        initComponents();
        
        this.visitorController = new VisitorController();
        loadVisitorsTable();
        cmbStatus.addItem("ACTIVO");
        cmbStatus.addItem("INACTIVO");
        cmbStatus.addItem("CON PASE");
        cmbStatus.addItem("SIN PASE");
        clearFields();
    }
    private void clearFields() {
        txtVisitorID.setText("");
        txtNameVisitor.setText("");
        txtVehiclePlate.setText(""); 
        txtUserID.setText("");
        chkHasPass.setSelected(false);
        cmbStatus.setSelectedIndex(0); 
        txtVisitorID.setEditable(true); 
    }
    private void loadVisitorsTable() {
        DefaultTableModel model = new DefaultTableModel();
        
        model.setColumnIdentifiers(new Object[]{
            "ID Visitante", 
            "Nombre", 
            "ID Residente", 
            "Placa Vehículo", 
            "Tiene Pase", 
            "Estado"
        });
        List<Visitor> visitors = visitorController.getAllVisitors();

        for (Visitor visitor : visitors) {
            model.addRow(new Object[]{
                visitor.getVisitorID(),
                visitor.getNameVisitor(),
                visitor.getUserID(),
                visitor.getVehiclePlate(), 
                visitor.isHasPass(),
                visitor.getLibraryVisitorStatus()
            });
        }
        tblVisitors.setModel(model);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblVisitorID = new javax.swing.JLabel();
        txtVisitorID = new java.awt.TextField();
        lblNameVisitor = new javax.swing.JLabel();
        txtNameVisitor = new java.awt.TextField();
        lblUserID = new javax.swing.JLabel();
        txtUserID = new java.awt.TextField();
        lblVehiclePlate = new javax.swing.JLabel();
        txtVehiclePlate = new java.awt.TextField();
        chkHasPass = new javax.swing.JCheckBox();
        lblStatus = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVisitors = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("REGISTRO DE VISITANTES");

        lblVisitorID.setText("ID Visitante:");

        txtVisitorID.setEditable(false);

        lblNameVisitor.setText("Nombre:");

        lblUserID.setText("ID Usuario:");

        lblVehiclePlate.setText("Placa del Vehiculo:");

        chkHasPass.setText("Tiene Pase");

        lblStatus.setText("Estado:");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo", "Con pase", "Sin pase" }));

        btnUpdate.setText("ACTUALIZAR");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setText("GUARDAR");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("ELIMINAR");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        tblVisitors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Visitante", "Nombre", "ID Residente", "Placa Vehículo", "Tiene Pase", "Estado"
            }
        ));
        tblVisitors.setToolTipText("");
        tblVisitors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVisitorsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblVisitors);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNameVisitor)
                                    .addComponent(lblVisitorID)
                                    .addComponent(lblUserID)
                                    .addComponent(lblVehiclePlate)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblStatus)
                                        .addGap(16, 16, 16))
                                    .addComponent(btnSave))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkHasPass)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtVisitorID, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                        .addComponent(txtNameVisitor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtUserID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtVehiclePlate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnUpdate)
                                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDelete))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVisitorID)
                    .addComponent(txtVisitorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNameVisitor)
                    .addComponent(txtNameVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserID))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVehiclePlate)
                    .addComponent(txtVehiclePlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(chkHasPass)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnSave)
                    .addComponent(btnDelete))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            if (txtVisitorID.getText().isEmpty() || txtNameVisitor.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El ID Visitante y el Nombre son campos obligatorios.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            Visitor newVisitor = new Visitor();
            newVisitor.setVisitorID(txtVisitorID.getText());
            newVisitor.setNameVisitor(txtNameVisitor.getText());
            newVisitor.setUserID(txtUserID.getText());
            newVisitor.setVehiclePlate(txtVehiclePlate.getText()); 
            newVisitor.setHasPass(chkHasPass.isSelected());
            newVisitor.setLibraryVisitorStatus((String) cmbStatus.getSelectedItem());

            // Llama al controlador para guardar
            visitorController.saveVisitor(newVisitor); 

            loadVisitorsTable();
            clearFields();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error al guardar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try {
            String visitorID = txtVisitorID.getText();
            if (txtVisitorID.isEditable() || visitorID.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un visitante de la tabla para actualizar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            Visitor updatedVisitor = new Visitor();
            updatedVisitor.setVisitorID(visitorID); 
            updatedVisitor.setNameVisitor(txtNameVisitor.getText());
            updatedVisitor.setUserID(txtUserID.getText());
            updatedVisitor.setVehiclePlate(txtVehiclePlate.getText()); 
            updatedVisitor.setHasPass(chkHasPass.isSelected());
            updatedVisitor.setLibraryVisitorStatus((String) cmbStatus.getSelectedItem());

            // Llama al controlador para actualizar
            if (visitorController.updateVisitor(updatedVisitor)) { 
                loadVisitorsTable();
                clearFields();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al actualizar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String idToDelete = txtVisitorID.getText();
        
        if (txtVisitorID.isEditable() || idToDelete.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un visitante de la tabla para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, 
                "¿Está seguro de que desea eliminar al visitante con ID: " + idToDelete + "?", 
                "Confirmar Eliminación", 
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            if (visitorController.deleteVisitor(idToDelete)) { 
                loadVisitorsTable();
                clearFields();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblVisitorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVisitorsMouseClicked
        int selectedRow = tblVisitors.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) tblVisitors.getModel();

            txtVisitorID.setText(model.getValueAt(selectedRow, 0).toString());
            txtNameVisitor.setText(model.getValueAt(selectedRow, 1).toString());
            txtUserID.setText(model.getValueAt(selectedRow, 2).toString());
            txtVehiclePlate.setText(model.getValueAt(selectedRow, 3).toString());
            chkHasPass.setSelected((Boolean) model.getValueAt(selectedRow, 4));
            cmbStatus.setSelectedItem(model.getValueAt(selectedRow, 5).toString());

            txtVisitorID.setEditable(false);
        }
    }//GEN-LAST:event_tblVisitorsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVisitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVisitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVisitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVisitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVisitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkHasPass;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNameVisitor;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblVehiclePlate;
    private javax.swing.JLabel lblVisitorID;
    private javax.swing.JTable tblVisitors;
    private java.awt.TextField txtNameVisitor;
    private java.awt.TextField txtUserID;
    private java.awt.TextField txtVehiclePlate;
    private java.awt.TextField txtVisitorID;
    // End of variables declaration//GEN-END:variables
}
